const TEROKA_DATA = {
  worlds: [
    {id:'space',name:'Angkasa',en:'Space',icon:'🌌',tag:'Planet, Moon & bintang',colors:['#15355f','#3b255d'],description:'Teroka Solar System, planet, Moon, bintang dan bagaimana kita bergerak di angkasa.',topics:['solar-system','sun','mercury','venus','earth','mars','jupiter','saturn','uranus','neptune','moon','rocket']},
    {id:'animals',name:'Dunia Haiwan',en:'Animals',icon:'🦁',tag:'Darat, laut & udara',colors:['#214c3d','#4b3c22'],description:'Kenali haiwan melalui habitat, makanan, anggota badan, bunyi dan fakta menarik.',topics:['elephant','lion','giraffe','tiger','zebra','penguin','dolphin','eagle']},
    {id:'vehicles',name:'Kenderaan',en:'Vehicles',icon:'🚗',tag:'Darat, udara & laut',colors:['#2c466a','#4a2e38'],description:'Lihat bagaimana kereta, kapal terbang, train dan mesin bergerak dan berfungsi.',topics:['car','airplane','train','ship','excavator','bicycle']},
    {id:'earth-world',name:'Bumi Kita',en:'Our Earth',icon:'🌍',tag:'Cuaca & fenomena alam',colors:['#17566a','#27495a'],description:'Kenapa hujan turun? Bagaimana gunung berapi terbentuk? Teroka sistem Bumi.',topics:['volcano','earthquake','rain','cloud','river','mountain']},
    {id:'ocean',name:'Lautan',en:'Ocean',icon:'🌊',tag:'Dunia di bawah air',colors:['#0d4964','#142f5c'],description:'Teroka hidupan laut, zon lautan, coral reef dan misteri laut dalam.',topics:['dolphin','shark','octopus','whale','coral','deep-sea']},
    {id:'dinosaurs',name:'Dinosaur',en:'Dinosaurs',icon:'🦖',tag:'Prasejarah',colors:['#42552c','#594126'],description:'Kenali dinosaur, zaman mereka hidup dan bagaimana saintis mengkaji fosil.',topics:['trex','triceratops','brachiosaurus','raptor','fossil']},
    {id:'plants',name:'Tumbuhan',en:'Plants',icon:'🌱',tag:'Hidup & membesar',colors:['#23563f','#344f29'],description:'Dari biji benih ke pokok. Fahami akar, daun, bunga dan fotosintesis.',topics:['seed','roots','leaf','flower','tree','photosynthesis']},
    {id:'body',name:'Tubuh Manusia',en:'Human Body',icon:'🧍',tag:'Kenali badan kita',colors:['#5b3044','#503d57'],description:'Teroka jantung, paru-paru, otak, tulang dan bagaimana badan bekerjasama.',topics:['heart','lungs','brain','bones','stomach','senses']},
    {id:'machines',name:'Bagaimana Ia Berfungsi',en:'How Things Work',icon:'⚙️',tag:'Mesin di sekeliling kita',colors:['#4b4230','#3d4657'],description:'Fahami benda biasa seperti lampu trafik, elevator, kipas dan elektrik.',topics:['traffic-light','fan','elevator','electricity']},
    {id:'world',name:'Negara & Dunia',en:'Countries & World',icon:'🗺️',tag:'Manusia & tempat',colors:['#3b3c64','#355467'],description:'Kenali benua, negara, budaya dan tempat-tempat menarik di dunia.',topics:['continents','malaysia','japan','egypt','flags']},
    {id:'science',name:'Sains',en:'Science',icon:'🧪',tag:'Eksperimen & konsep',colors:['#513d6b','#244e5c'],description:'Belajar konsep sains melalui contoh mudah, visual dan eksperimen selamat.',topics:['gravity','magnet','light','sound','states']},
    {id:'technology',name:'Teknologi',en:'Technology',icon:'🛰️',tag:'Ciptaan manusia',colors:['#21455e','#37365d'],description:'Bagaimana satelit, internet, robot dan komputer membantu manusia.',topics:['satellite','internet','robot','computer']},
    {id:'english',name:'English World',en:'English World',icon:'🗣️',tag:'Vocabulary, sentence & conversation',colors:['#2d315f','#135260'],description:'Belajar English secara visual dan santai — dengar, faham, bina ayat dan guna dalam situasi sebenar.',topics:['english-first-words','english-home','english-animals','english-food','english-actions','english-feelings','english-body','english-colors','sentence-builder','conversation','mini-story','word-hunt']}
  ],
  topics: {
    'solar-system':{world:'space',name:'Solar System',ms:'Sistem Suria',icon:'🪐',short:'Matahari dan semua objek yang mengorbitnya.',summary:{explorer:'Sistem Suria ialah keluarga besar di angkasa. Matahari berada di tengah dan planet bergerak mengelilinginya.',discoverer:'Sistem Suria terdiri daripada Matahari, lapan planet, bulan, asteroid, komet dan objek kecil lain yang terikat oleh graviti.',investigator:'Sistem Suria terbentuk kira-kira 4.6 bilion tahun lalu daripada awan gas dan debu. Graviti Matahari mengekalkan planet dan objek lain dalam orbit.'},facts:[['☀️','Pusat','Matahari ialah bintang di tengah Sistem Suria.'],['8️⃣','Planet','Terdapat lapan planet utama.'],['🌀','Orbit','Setiap planet bergerak mengelilingi Matahari pada orbitnya.'],['🌌','Galaksi','Sistem Suria kita berada dalam galaksi Milky Way.']],why:['Kenapa planet tak jatuh ke Matahari?','Graviti menarik planet ke arah Matahari, tetapi planet juga bergerak ke hadapan dengan laju. Gabungan dua gerakan ini menghasilkan orbit.'],mode:'solar'},
    sun:{world:'space',name:'Sun',ms:'Matahari',icon:'☀️',short:'Bintang yang membekalkan cahaya dan haba kepada Bumi.',summary:{explorer:'Matahari ialah bintang yang sangat panas. Cahaya Matahari membantu tumbuhan dan memberi haba kepada Bumi.',discoverer:'Matahari ialah bintang yang paling dekat dengan Bumi dan mengandungi hampir semua jisim Sistem Suria.',investigator:'Matahari ialah bintang jenis G yang menghasilkan tenaga melalui nuclear fusion, apabila hidrogen bergabung membentuk helium di terasnya.'},facts:[['🔥','Sangat panas','Bahagian permukaannya sekitar 5,500°C.'],['💡','Sumber tenaga','Cahaya Matahari mengambil kira-kira 8 minit untuk sampai ke Bumi.'],['📏','Sangat besar','Lebih satu juta Bumi boleh dimuatkan dalam isipadu Matahari.']],why:['Kenapa kita tak boleh tengok Matahari terus?','Cahaya Matahari sangat kuat dan boleh merosakkan mata. Gunakan perlindungan khas untuk pemerhatian solar.']},
    mercury:{world:'space',name:'Mercury',ms:'Utarid',icon:'🪨',short:'Planet paling dekat dengan Matahari.',summary:{explorer:'Mercury kecil dan paling dekat dengan Matahari.',discoverer:'Mercury ialah planet terkecil dan bergerak mengelilingi Matahari paling cepat.',investigator:'Mercury ialah planet berbatu dengan atmosfera sangat nipis, menyebabkan perubahan suhu siang dan malam yang besar.'},facts:[['1️⃣','Planet pertama','Paling dekat dengan Matahari.'],['⏱️','Tahun pendek','Satu tahun Mercury hanya sekitar 88 hari Bumi.'],['🌙','Tiada moon','Mercury tidak mempunyai bulan.']]},
    venus:{world:'space',name:'Venus',ms:'Zuhrah',icon:'🟡',short:'Planet panas yang diselubungi awan tebal.',summary:{explorer:'Venus hampir sebesar Bumi tetapi sangat panas.',discoverer:'Venus mempunyai atmosfera karbon dioksida yang sangat tebal dan permukaannya lebih panas daripada Mercury.',investigator:'Greenhouse effect yang sangat kuat memerangkap haba di Venus, menjadikannya planet terpanas dalam Sistem Suria.'},facts:[['🌡️','Sangat panas','Suhu permukaan sekitar 465°C.'],['☁️','Awan tebal','Awan mengandungi titisan asid sulfurik.'],['🔄','Putaran pelik','Venus berputar berlawanan arah berbanding kebanyakan planet.']]},
    earth:{world:'space',name:'Earth',ms:'Bumi',icon:'🌍',short:'Rumah kita — planet yang mempunyai air cecair dan kehidupan.',summary:{explorer:'Bumi ialah rumah kita. Ada daratan, lautan, udara dan banyak hidupan.',discoverer:'Bumi ialah planet ketiga dari Matahari dan satu-satunya dunia yang kita tahu mempunyai kehidupan.',investigator:'Bumi mempunyai atmosfera kaya nitrogen dan oksigen, air cecair yang banyak serta medan magnet yang membantu melindungi kehidupan.'},facts:[['3️⃣','Planet ketiga','Bumi berada selepas Mercury dan Venus.'],['🌙','Satu Moon','Bumi mempunyai satu satelit semula jadi.'],['💧','Banyak air','Kira-kira 71% permukaan Bumi diliputi air.']],why:['Kenapa Bumi nampak biru dari angkasa?','Kerana sebahagian besar permukaan Bumi diliputi lautan, dan atmosfera juga menyebarkan cahaya biru.']},
    mars:{world:'space',name:'Mars',ms:'Marikh',icon:'🔴',short:'Planet merah yang mempunyai gunung berapi gergasi.',summary:{explorer:'Mars dipanggil planet merah kerana tanahnya nampak kemerahan.',discoverer:'Mars ialah planet berbatu yang sejuk dengan atmosfera nipis dan mempunyai dua bulan kecil.',investigator:'Warna merah Mars datang daripada iron oxide dalam tanah. Bukti geologi menunjukkan air cecair pernah mengalir di permukaannya pada masa lalu.'},facts:[['🔴','Planet merah','Iron oxide memberi warna kemerahan.'],['🌋','Olympus Mons','Antara gunung berapi terbesar dalam Sistem Suria.'],['🌙','2 moons','Phobos dan Deimos.']]},
    jupiter:{world:'space',name:'Jupiter',ms:'Musytari',icon:'🟤',short:'Planet terbesar dalam Sistem Suria.',summary:{explorer:'Jupiter sangat besar dan penuh dengan gas.',discoverer:'Jupiter ialah gas giant terbesar dan mempunyai ribut besar yang dikenali sebagai Great Red Spot.',investigator:'Jupiter kebanyakannya terdiri daripada hidrogen dan helium. Medan magnetnya sangat kuat dan sistem bulannya membentuk dunia kecil yang kompleks.'},facts:[['🏆','Paling besar','Planet terbesar dalam Sistem Suria.'],['🌪️','Great Red Spot','Ribut gergasi yang telah diperhatikan selama berabad-abad.'],['🌙','Banyak moon','Jupiter mempunyai banyak satelit semula jadi.']]},
    saturn:{world:'space',name:'Saturn',ms:'Zuhal',icon:'🪐',short:'Gas giant terkenal dengan sistem cincin yang cantik.',summary:{explorer:'Saturn ialah planet besar dengan cincin yang mudah dikenali.',discoverer:'Cincin Saturn terdiri daripada banyak ketulan ais dan batu yang mengorbit planet.',investigator:'Saturn ialah gas giant yang sangat kurang tumpat. Sistem cincinnya terdiri daripada zarah dari saiz debu hingga bongkah besar yang bergerak pada orbit berbeza.'},facts:[['💍','Cincin','Cincin utama terdiri daripada ais dan batu.'],['6️⃣','Planet keenam','Saturn ialah planet ke-6 dari Matahari.'],['🪶','Ketumpatan rendah','Purata ketumpatan Saturn lebih rendah daripada air.']],why:['Kenapa Saturn ada cincin?','Cincin mungkin terbentuk daripada bahan bulan, komet atau asteroid yang pecah akibat perlanggaran dan daya graviti.']},
    uranus:{world:'space',name:'Uranus',ms:'Uranus',icon:'🩵',short:'Ice giant yang berputar hampir mengiring.',summary:{explorer:'Uranus berwarna biru pucat dan nampak seperti bergolek semasa mengorbit.',discoverer:'Paksi Uranus sangat condong, jadi planet ini berputar hampir pada sisinya.',investigator:'Methane dalam atmosfera menyerap cahaya merah dan membantu menghasilkan warna biru-hijau Uranus. Kecondongan paksi sekitar 98° menghasilkan musim yang ekstrem.'},facts:[['↩️','Paksi condong','Uranus hampir berputar pada sisinya.'],['🧊','Ice giant','Mengandungi bahan seperti air, ammonia dan methane dalam interior.'],['💍','Ada cincin','Uranus juga mempunyai sistem cincin nipis.']]},
    neptune:{world:'space',name:'Neptune',ms:'Neptun',icon:'🔵',short:'Planet paling jauh dengan angin yang sangat laju.',summary:{explorer:'Neptune ialah planet biru yang sangat jauh dan sejuk.',discoverer:'Neptune ialah ice giant dan mempunyai antara angin terpantas dalam Sistem Suria.',investigator:'Neptune menerima sedikit tenaga daripada Matahari tetapi masih mempunyai cuaca dinamik, ribut besar dan angin berkelajuan sangat tinggi.'},facts:[['8️⃣','Planet kelapan','Paling jauh antara lapan planet utama.'],['💨','Angin laju','Angin boleh melebihi 2,000 km/j.'],['🧊','Sangat sejuk','Berada jauh daripada Matahari.']]},
    moon:{world:'space',name:'Moon',ms:'Bulan',icon:'🌙',short:'Satelit semula jadi Bumi.',summary:{explorer:'Bulan bergerak mengelilingi Bumi dan kita nampak bentuknya berubah sepanjang bulan.',discoverer:'Fasa Bulan berubah kerana kita melihat bahagian yang disinari Matahari dari sudut berbeza.',investigator:'Bulan terikat secara tidal kepada Bumi, jadi sisi yang sama hampir sentiasa menghadap kita. Gravitinya juga mempengaruhi pasang surut laut.'},facts:[['🌊','Pasang surut','Graviti Bulan membantu menghasilkan tides.'],['👣','Manusia pernah ke sana','Astronaut Apollo pernah berjalan di Bulan.'],['🔄','Orbit','Bulan mengambil kira-kira 27.3 hari untuk mengorbit Bumi.']]},
    rocket:{world:'space',name:'Rocket',ms:'Roket',icon:'🚀',short:'Kenderaan yang membawa muatan atau manusia ke angkasa.',summary:{explorer:'Roket menolak gas ke bawah dengan sangat laju supaya ia boleh bergerak ke atas.',discoverer:'Roket menghasilkan thrust dengan membuang gas berkelajuan tinggi ke arah bertentangan.',investigator:'Propulsion roket mengikuti prinsip momentum dan Newton’s third law. Roket membawa fuel dan oxidizer sendiri, jadi ia boleh berfungsi dalam vakum.'},facts:[['⬆️','Thrust','Daya yang menolak roket ke hadapan.'],['🧯','Fuel','Roket memerlukan propellant untuk menghasilkan gas panas.'],['🛰️','Payload','Boleh membawa satelit, probe atau manusia.']]},

    elephant:{world:'animals',name:'Elephant',ms:'Gajah',icon:'🐘',short:'Mamalia darat terbesar dengan belalai serba guna.',summary:{explorer:'Gajah sangat besar. Belalainya digunakan untuk bernafas, menghidu, minum dan mengambil makanan.',discoverer:'Gajah hidup dalam kumpulan sosial dan menggunakan belalai serta telinga besar untuk banyak fungsi.',investigator:'Gajah mempunyai komunikasi kompleks termasuk bunyi frekuensi rendah. Telinga besar membantu thermoregulation dengan melepaskan haba.'},facts:[['👃','Belalai','Gabungan hidung dan bibir atas yang sangat fleksibel.'],['👂','Telinga besar','Membantu menyejukkan badan.'],['🌿','Herbivore','Makan rumput, daun, kulit kayu dan buah.']],why:['Kenapa telinga gajah sangat besar?','Permukaan telinga yang besar membantu darah melepaskan haba, terutama dalam cuaca panas.']},
    lion:{world:'animals',name:'Lion',ms:'Singa',icon:'🦁',short:'Kucing besar yang hidup dalam kumpulan.',summary:{explorer:'Singa ialah kucing besar. Banyak singa hidup bersama dalam kumpulan yang dipanggil pride.',discoverer:'Singa ialah predator sosial dan kebanyakannya hidup di savanna serta grassland Afrika.',investigator:'Struktur sosial pride membantu perlindungan wilayah dan penjagaan anak. Singa berkomunikasi melalui roar, bau dan bahasa badan.'},facts:[['👥','Pride','Kumpulan sosial singa.'],['🍖','Carnivore','Makan daging.'],['📣','Roar','Ngauman boleh didengar dari jarak jauh.']]},
    giraffe:{world:'animals',name:'Giraffe',ms:'Zirafah',icon:'🦒',short:'Haiwan darat paling tinggi.',summary:{explorer:'Zirafah mempunyai leher panjang untuk mencapai daun di tempat tinggi.',discoverer:'Zirafah menggunakan lidah panjang dan kuat untuk mengambil daun, termasuk daripada pokok berduri.',investigator:'Walaupun leher sangat panjang, zirafah mempunyai tujuh vertebra leher seperti manusia; setiap vertebra cuma jauh lebih panjang.'},facts:[['📏','Sangat tinggi','Haiwan darat tertinggi.'],['👅','Lidah panjang','Membantu mencapai daun.'],['7️⃣','Tujuh tulang leher','Bilangan vertebra serviks sama seperti manusia.']]},
    tiger:{world:'animals',name:'Tiger',ms:'Harimau',icon:'🐯',short:'Kucing besar bercorak belang unik.',summary:{explorer:'Setiap harimau mempunyai corak belang yang berbeza.',discoverer:'Harimau biasanya hidup bersendirian dan menggunakan belang sebagai camouflage.',investigator:'Corak belang turut terdapat pada kulit, bukan hanya bulu. Ia membantu memecahkan bentuk badan dalam habitat vegetasi.'},facts:[['🟧','Belang unik','Corak setiap harimau tidak sama.'],['🏊','Pandai berenang','Harimau biasanya selesa berada dalam air.'],['🍖','Predator','Memburu pelbagai haiwan.']]},
    zebra:{world:'animals',name:'Zebra',ms:'Zebra',icon:'🦓',short:'Mamalia Afrika dengan belang hitam putih.',summary:{explorer:'Zebra nampak seperti kuda dengan belang hitam putih.',discoverer:'Belang zebra mungkin membantu mengelirukan serangga penghisap darah dan juga mempunyai fungsi sosial.',investigator:'Kajian menunjukkan corak belang boleh mengurangkan pendaratan biting flies. Setiap individu mempunyai corak unik.'},facts:[['🖤','Belang unik','Tiada dua zebra bercorak tepat sama.'],['🌿','Herbivore','Banyak makan rumput.'],['👥','Berkumpulan','Sering hidup dalam herd.']]},
    penguin:{world:'animals',name:'Penguin',ms:'Penguin',icon:'🐧',short:'Burung yang tidak terbang tetapi sangat cekap berenang.',summary:{explorer:'Penguin tak boleh terbang di udara tetapi berenang dengan sangat baik.',discoverer:'Sayap penguin berubah menjadi flipper yang membantu bergerak di dalam air.',investigator:'Badan streamline, tulang padat dan lapisan bulu serta lemak membantu penguin hidup dan berenang dalam persekitaran sejuk.'},facts:[['🏊','Perenang','Flipper memberi tolakan dalam air.'],['🪶','Burung','Penguin tetap mempunyai bulu.'],['🐟','Makanan','Makan ikan, krill dan haiwan laut kecil.']]},
    dolphin:{world:'animals',name:'Dolphin',ms:'Ikan Lumba-lumba',icon:'🐬',short:'Mamalia laut pintar yang bernafas dengan paru-paru.',summary:{explorer:'Dolphin hidup di air tetapi perlu naik ke permukaan untuk bernafas.',discoverer:'Dolphin ialah mamalia, bukan ikan. Ia menggunakan blowhole dan boleh menggunakan echolocation.',investigator:'Echolocation membolehkan dolphin menghantar bunyi dan menilai gema untuk memahami jarak, bentuk dan lokasi objek.'},facts:[['🫁','Bernafas udara','Menggunakan paru-paru.'],['🔊','Echolocation','Menggunakan bunyi untuk mengesan objek.'],['👥','Sosial','Banyak spesies hidup dalam pod.']]},
    eagle:{world:'animals',name:'Eagle',ms:'Helang',icon:'🦅',short:'Burung pemangsa dengan penglihatan tajam.',summary:{explorer:'Helang boleh melihat mangsa dari jauh dan mempunyai cakar yang kuat.',discoverer:'Helang ialah raptor yang mempunyai paruh melengkung, talon kuat dan penglihatan tajam.',investigator:'Mata raptor mempunyai kepadatan photoreceptor tinggi dan adaptasi visual yang membantu mengesan objek kecil dari jarak jauh.'},facts:[['👀','Penglihatan','Sangat baik untuk mengesan mangsa.'],['🦶','Talon','Cakar kuat untuk menangkap.'],['🪶','Raptor','Kumpulan burung pemangsa.']]},

    car:{world:'vehicles',name:'Car',ms:'Kereta',icon:'🚗',short:'Kenderaan jalan raya dengan empat roda.',summary:{explorer:'Kereta menggunakan enjin atau motor untuk memusingkan roda.',discoverer:'Kereta menukar tenaga daripada fuel atau battery menjadi gerakan pada roda.',investigator:'Powertrain menghantar torque ke roda melalui komponen mekanikal atau motor elektrik, sementara steering dan braking mengawal arah serta kelajuan.'},facts:[['⚙️','Power','Enjin atau motor menghasilkan kuasa.'],['🛞','Roda','Memberi cengkaman pada jalan.'],['🛑','Brake','Mengurangkan kelajuan melalui friction atau regenerative braking.']]},
    airplane:{world:'vehicles',name:'Airplane',ms:'Kapal Terbang',icon:'✈️',short:'Kenderaan udara yang menghasilkan lift pada sayap.',summary:{explorer:'Sayap membantu kapal terbang terangkat apabila ia bergerak melalui udara.',discoverer:'Empat daya utama ialah lift, weight, thrust dan drag.',investigator:'Bentuk aerofoil dan sudut serangan mengubah tekanan serta momentum aliran udara, menghasilkan lift. Engine pula menyediakan thrust untuk mengatasi drag.'},facts:[['⬆️','Lift','Daya yang membantu naik.'],['➡️','Thrust','Menolak aircraft ke hadapan.'],['⬇️','Weight','Graviti menarik ke bawah.'],['⬅️','Drag','Rintangan udara.']],why:['Macam mana kapal terbang yang berat boleh terbang?','Apabila bergerak cukup laju, sayap menghasilkan lift. Jika lift mengatasi weight, aircraft boleh naik.']},
    train:{world:'vehicles',name:'Train',ms:'Kereta Api',icon:'🚆',short:'Kenderaan rel yang membawa ramai penumpang atau barang.',summary:{explorer:'Train bergerak di atas rel dan boleh membawa ramai orang.',discoverer:'Roda keluli di atas rel keluli menghasilkan rolling resistance yang rendah, jadi train efisien untuk membawa beban besar.',investigator:'Rail guidance mengurangkan keperluan steering dan friction rolling yang rendah menjadikan pengangkutan rel sangat sesuai untuk kapasiti tinggi.'},facts:[['🛤️','Rel','Memandu arah perjalanan.'],['⚡','Kuasa','Boleh guna elektrik atau diesel.'],['🚉','Stesen','Tempat penumpang naik dan turun.']]},
    ship:{world:'vehicles',name:'Ship',ms:'Kapal',icon:'🚢',short:'Kenderaan besar yang terapung dan bergerak di air.',summary:{explorer:'Kapal terapung kerana air menolak badan kapal ke atas.',discoverer:'Buoyancy membantu kapal terapung apabila berat air yang dipindahkan cukup untuk menampung berat kapal.',investigator:'Prinsip Archimedes menerangkan bahawa daya apungan bersamaan berat fluid yang dipindahkan. Hull direka untuk displacement dan stability.'},facts:[['🌊','Buoyancy','Daya air menolak ke atas.'],['⚓','Anchor','Membantu kapal kekal di lokasi.'],['🌀','Propeller','Menghasilkan thrust dalam air.']]},
    excavator:{world:'vehicles',name:'Excavator',ms:'Jengkaut',icon:'🚜',short:'Mesin pembinaan untuk menggali dan mengangkat.',summary:{explorer:'Excavator ada lengan besar untuk menggali tanah.',discoverer:'Sistem hydraulic menggunakan cecair bertekanan untuk menggerakkan boom, arm dan bucket.',investigator:'Hydraulic cylinders menukar tekanan fluid kepada daya linear yang sangat besar, membolehkan excavator mengangkat dan menggali beban berat.'},facts:[['💪','Hydraulic','Memberi daya besar.'],['🪣','Bucket','Menggali dan mengangkat.'],['⛓️','Tracks','Menyebarkan berat di permukaan.']]},
    bicycle:{world:'vehicles',name:'Bicycle',ms:'Basikal',icon:'🚲',short:'Kenderaan dua roda yang digerakkan oleh kayuhan.',summary:{explorer:'Apabila kita kayuh pedal, rantai membantu memusingkan roda belakang.',discoverer:'Gear membolehkan penunggang mengubah hubungan antara kelajuan kayuhan dan daya pada roda.',investigator:'Drivetrain menggunakan crank, chain dan sprocket. Gear ratio menentukan mechanical advantage dan kelajuan roda bagi setiap putaran pedal.'},facts:[['🦵','Pedal','Tenaga datang daripada kaki.'],['⛓️','Chain','Memindahkan putaran.'],['⚙️','Gear','Mengubah effort dan kelajuan.']]},

    volcano:{world:'earth-world',name:'Volcano',ms:'Gunung Berapi',icon:'🌋',short:'Tempat magma dari dalam Bumi boleh sampai ke permukaan.',summary:{explorer:'Gunung berapi boleh mengeluarkan lava, gas dan abu.',discoverer:'Magma naik melalui kerak Bumi. Apabila sampai ke permukaan, ia dipanggil lava.',investigator:'Volcanism berkait dengan pergerakan magma, tectonic setting, gas terlarut dan tekanan. Jenis magma mempengaruhi gaya letusan.'},facts:[['🔥','Magma → lava','Magma dipanggil lava apabila keluar ke permukaan.'],['🌫️','Abu & gas','Letusan boleh melepaskan bahan selain lava.'],['🧱','Bina tanah baru','Lava yang sejuk menjadi batu.']],why:['Kenapa gunung berapi meletup?','Gas dan magma boleh terkumpul di bawah tekanan. Apabila tekanan melebihi kekuatan batu di sekeliling, bahan boleh keluar melalui rekahan atau vent.']},
    earthquake:{world:'earth-world',name:'Earthquake',ms:'Gempa Bumi',icon:'🫨',short:'Gegaran apabila tenaga dilepaskan dalam kerak Bumi.',summary:{explorer:'Gempa berlaku apabila batu di dalam Bumi bergerak secara tiba-tiba.',discoverer:'Tekanan boleh terkumpul di sepanjang fault. Apabila batu tergelincir, tenaga bergerak sebagai seismic waves.',investigator:'Elastic strain yang terkumpul di crust dilepaskan semasa fault rupture. Seismic waves merambat melalui dan di sepanjang permukaan Bumi.'},facts:[['🪨','Fault','Retakan tempat batu bergerak.'],['〰️','Seismic waves','Gelombang membawa tenaga.'],['📍','Epicenter','Titik di permukaan di atas sumber gempa.']]},
    rain:{world:'earth-world',name:'Rain',ms:'Hujan',icon:'🌧️',short:'Air yang jatuh dari awan selepas titisan menjadi cukup besar.',summary:{explorer:'Air naik sebagai wap, membentuk awan dan akhirnya jatuh semula sebagai hujan.',discoverer:'Dalam water cycle, air menyejat, memeluwap menjadi titisan awan dan jatuh sebagai precipitation.',investigator:'Condensation berlaku apabila udara lembap menyejuk. Droplet membesar melalui collision/coalescence atau proses ais sehingga gravity mengatasi daya udara.'},facts:[['☀️','Evaporation','Haba membantu air menjadi wap.'],['☁️','Condensation','Wap menyejuk dan membentuk titisan.'],['🌧️','Precipitation','Air jatuh apabila cukup berat.']]},
    cloud:{world:'earth-world',name:'Cloud',ms:'Awan',icon:'☁️',short:'Kumpulan titisan air atau kristal ais kecil di udara.',summary:{explorer:'Awan terbentuk apabila wap air menyejuk menjadi titisan yang sangat kecil.',discoverer:'Awan terdiri daripada titisan air atau kristal ais yang terapung dalam udara.',investigator:'Air parcel yang naik mengembang dan menyejuk. Apabila mencapai saturation, condensation pada aerosol menghasilkan cloud droplets.'},facts:[['💧','Titisan kecil','Awan bukan "wap" semata-mata.'],['⬆️','Udara naik','Cooling membantu pembentukan awan.'],['🌦️','Cuaca','Jenis awan memberi petunjuk keadaan atmosfera.']]},
    river:{world:'earth-world',name:'River',ms:'Sungai',icon:'🏞️',short:'Air yang mengalir dari kawasan tinggi menuju tasik atau laut.',summary:{explorer:'Sungai mengalir menuruni bukit kerana graviti.',discoverer:'Air dari hujan dan mata air berkumpul dalam drainage basin lalu mengalir melalui sungai.',investigator:'River discharge, slope dan sediment load mempengaruhi erosion, transport dan deposition sepanjang channel.'},facts:[['⬇️','Graviti','Mendorong air ke tempat lebih rendah.'],['🪨','Erosion','Air boleh menghakis batu dan tanah.'],['🌊','Muara','Banyak sungai berakhir di laut atau tasik.']]},
    mountain:{world:'earth-world',name:'Mountain',ms:'Gunung',icon:'🏔️',short:'Bentuk muka bumi yang tinggi dan curam.',summary:{explorer:'Gunung ialah kawasan tanah yang sangat tinggi.',discoverer:'Banyak gunung terbentuk apabila tectonic plates bertembung atau melalui aktiviti gunung berapi.',investigator:'Orogeny melibatkan deformation, uplift dan erosion. Plate convergence menghasilkan banyak banjaran gunung utama.'},facts:[['⬆️','Tinggi','Lebih tinggi daripada kawasan sekeliling.'],['🧊','Sejuk','Udara biasanya lebih sejuk di altitud tinggi.'],['🪨','Geologi','Boleh terbentuk melalui tectonics atau volcanism.']]},

    shark:{world:'ocean',name:'Shark',ms:'Jerung',icon:'🦈',short:'Ikan pemangsa dengan rangka daripada cartilage.',summary:{explorer:'Jerung ialah ikan dan mempunyai banyak gigi yang sentiasa diganti.',discoverer:'Jerung mempunyai rangka cartilage, bukan tulang seperti kebanyakan vertebrata.',investigator:'Shark sensory systems termasuk electroreception yang dapat mengesan medan elektrik lemah daripada otot haiwan lain.'},facts:[['🦴','Cartilage','Rangka lebih fleksibel daripada tulang.'],['🦷','Gigi berganti','Banyak spesies menggantikan gigi berulang kali.'],['⚡','Electroreception','Boleh mengesan signal elektrik lemah.']]},
    octopus:{world:'ocean',name:'Octopus',ms:'Sotong Kurita',icon:'🐙',short:'Haiwan laut pintar dengan lapan lengan.',summary:{explorer:'Octopus ada lapan lengan dan boleh menukar warna badan.',discoverer:'Octopus menggunakan chromatophores untuk mengubah rupa dan banyak neuron berada dalam lengannya.',investigator:'Cephalopod nervous system sangat distributed; kawalan lengan mempunyai tahap autonomy tinggi. Camouflage melibatkan pigment dan struktur kulit.'},facts:[['8️⃣','Lapan lengan','Setiap lengan sangat fleksibel.'],['🎨','Camouflage','Boleh ubah warna dan tekstur.'],['🧠','Pintar','Mampu menyelesaikan masalah.']]},
    whale:{world:'ocean',name:'Whale',ms:'Paus',icon:'🐋',short:'Mamalia laut besar yang bernafas udara.',summary:{explorer:'Paus hidup dalam laut tetapi bernafas dengan paru-paru.',discoverer:'Paus ialah mamalia; anak menyusu dan mereka perlu naik ke permukaan untuk bernafas.',investigator:'Cetaceans mempunyai adaptasi diving seperti oxygen storage tinggi dalam darah dan otot serta kawalan circulation semasa menyelam.'},facts:[['🫁','Paru-paru','Perlu ke permukaan.'],['🍼','Mamalia','Anak menyusu.'],['🎵','Bunyi','Sesetengah spesies berkomunikasi dengan vokalisasi kompleks.']]},
    coral:{world:'ocean',name:'Coral Reef',ms:'Terumbu Karang',icon:'🪸',short:'Ekosistem yang dibina oleh koloni haiwan coral kecil.',summary:{explorer:'Coral nampak macam batu atau tumbuhan tetapi sebenarnya dibina oleh haiwan kecil.',discoverer:'Coral polyps membina rangka calcium carbonate dan banyak hidup bersama algae symbiotic.',investigator:'Reef-building corals mendapat banyak tenaga daripada photosynthetic dinoflagellates. Heat stress boleh menyebabkan bleaching apabila hubungan symbiosis terganggu.'},facts:[['🐚','Haiwan kecil','Coral polyps ialah haiwan.'],['🏠','Habitat','Reef menjadi rumah kepada banyak spesies.'],['🌡️','Sensitif haba','Air terlalu panas boleh menyebabkan bleaching.']]},
    'deep-sea':{world:'ocean',name:'Deep Sea',ms:'Laut Dalam',icon:'🌑',short:'Bahagian lautan yang gelap, sejuk dan bertekanan tinggi.',summary:{explorer:'Di laut sangat dalam, cahaya Matahari hampir tiada.',discoverer:'Haiwan laut dalam mempunyai adaptasi seperti bioluminescence dan badan yang sesuai dengan tekanan tinggi.',investigator:'Below the photic zone, ecosystems bergantung pada organic material yang tenggelam, predation, atau chemosynthesis di lokasi tertentu seperti hydrothermal vents.'},facts:[['🌑','Gelap','Cahaya semakin berkurang dengan kedalaman.'],['💡','Bioluminescence','Sesetengah haiwan menghasilkan cahaya sendiri.'],['⬇️','Tekanan tinggi','Pressure meningkat dengan depth.']]},

    trex:{world:'dinosaurs',name:'Tyrannosaurus rex',ms:'T. rex',icon:'🦖',short:'Theropod besar dari akhir Cretaceous.',summary:{explorer:'T. rex ialah dinosaur pemakan daging yang besar dengan gigi kuat.',discoverer:'T. rex hidup pada akhir zaman Cretaceous dan mempunyai deria bau serta gigitan yang sangat kuat.',investigator:'Tyrannosaurus rex ialah tyrannosaurid theropod yang hidup kira-kira 68–66 juta tahun lalu di Amerika Utara.'},facts:[['🦷','Gigi kuat','Direka untuk menggigit dan menghancurkan.'],['🦵','Dua kaki','Bipedal theropod.'],['🕰️','Cretaceous','Hidup dekat penghujung era dinosaur non-avian.']]},
    triceratops:{world:'dinosaurs',name:'Triceratops',ms:'Triceratops',icon:'🦕',short:'Dinosaur herbivore dengan tiga tanduk dan frill.',summary:{explorer:'Triceratops mempunyai tiga tanduk di kepala.',discoverer:'Triceratops ialah herbivore besar yang hidup pada zaman yang sama dengan T. rex.',investigator:'Ceratopsid ini mempunyai skull besar, frill dan tiga horn. Fungsi struktur mungkin melibatkan defence, display dan species recognition.'},facts:[['3️⃣','Tiga tanduk','Dua di atas mata, satu di hidung.'],['🌿','Herbivore','Makan tumbuhan.'],['🛡️','Frill','Struktur besar di belakang kepala.']]},
    brachiosaurus:{world:'dinosaurs',name:'Brachiosaurus',ms:'Brachiosaurus',icon:'🦕',short:'Sauropod tinggi dengan leher sangat panjang.',summary:{explorer:'Brachiosaurus boleh mencapai daun tinggi dengan leher panjang.',discoverer:'Kaki hadapannya lebih panjang daripada kaki belakang, memberi postur bahu yang tinggi.',investigator:'Brachiosaurus ialah sauropod Jurassic yang mempunyai forelimbs panjang, thorax besar dan leher tinggi berbanding banyak sauropod lain.'},facts:[['🦒','Leher panjang','Membantu mencapai vegetasi tinggi.'],['🌿','Herbivore','Makan tumbuhan.'],['🦵','Kaki depan panjang','Ciri utama genus ini.']]},
    raptor:{world:'dinosaurs',name:'Velociraptor',ms:'Velociraptor',icon:'🐉',short:'Dromaeosaur kecil berbulu dengan claw pada kaki.',summary:{explorer:'Velociraptor lebih kecil daripada yang biasa ditunjukkan dalam filem.',discoverer:'Velociraptor sebenar kira-kira sebesar turkey besar dan mempunyai bulu.',investigator:'Fossil evidence menunjukkan dromaeosaurids termasuk Velociraptor mempunyai feather-related structures. Ia hidup di Asia pada Late Cretaceous.'},facts:[['🪶','Berbulu','Evidence menyokong feathering.'],['📏','Lebih kecil','Bukan sebesar manusia dewasa seperti dalam sesetengah filem.'],['🦶','Sickle claw','Mempunyai claw melengkung pada kaki.']]},
    fossil:{world:'dinosaurs',name:'Fossil',ms:'Fosil',icon:'🦴',short:'Bukti kehidupan lampau yang terpelihara dalam batu atau bahan lain.',summary:{explorer:'Fosil boleh jadi tulang, tapak kaki atau kesan hidupan lama.',discoverer:'Fossil membantu paleontologist mengetahui rupa, umur dan cara hidup organisma purba.',investigator:'Fossilization memerlukan keadaan tertentu. Dating relatif dan radiometric dating membantu meletakkan fossil dalam konteks geologi.'},facts:[['🦴','Body fossil','Bahagian organisma yang terpelihara.'],['👣','Trace fossil','Kesan seperti footprint atau burrow.'],['🔬','Evidence','Digunakan untuk reconstruct kehidupan lampau.']]},

    seed:{world:'plants',name:'Seed',ms:'Biji Benih',icon:'🌰',short:'Struktur kecil yang mengandungi embrio tumbuhan.',summary:{explorer:'Biji benih boleh tumbuh menjadi pokok baru apabila mendapat air dan keadaan sesuai.',discoverer:'Seed mengandungi embryo dan bekalan makanan awal, dilindungi oleh seed coat.',investigator:'Germination bermula apabila keadaan seperti water, oxygen dan temperature sesuai mengaktifkan metabolism embryo.'},facts:[['💧','Air','Mencetuskan proses germination.'],['🌱','Embryo','Tumbuhan kecil berada di dalam seed.'],['🛡️','Seed coat','Melindungi isi seed.']]},
    roots:{world:'plants',name:'Roots',ms:'Akar',icon:'🪴',short:'Bahagian yang menyerap air dan membantu memegang tumbuhan.',summary:{explorer:'Akar masuk ke dalam tanah untuk mengambil air dan memegang pokok.',discoverer:'Root menyerap air dan mineral melalui permukaan, termasuk root hairs.',investigator:'Root systems anchor plants, store resources dan menyerap water/mineral ions. Root hairs meningkatkan surface area.'},facts:[['💧','Serap air','Mengambil air dari tanah.'],['⚓','Anchor','Memegang tumbuhan.'],['🧂','Mineral','Mengambil ion mineral penting.']]},
    leaf:{world:'plants',name:'Leaf',ms:'Daun',icon:'🍃',short:'Bahagian utama tumbuhan menangkap cahaya untuk fotosintesis.',summary:{explorer:'Daun menangkap cahaya Matahari untuk membantu tumbuhan membuat makanan.',discoverer:'Chlorophyll dalam daun menyerap cahaya yang digunakan dalam photosynthesis.',investigator:'Gas exchange berlaku melalui stomata, sementara chloroplast menjalankan reactions photosynthesis yang menukar light energy kepada chemical energy.'},facts:[['☀️','Cahaya','Daun menangkap light.'],['🟢','Chlorophyll','Pigment penting untuk photosynthesis.'],['💨','Stomata','Lubang kecil untuk gas exchange.']]},
    flower:{world:'plants',name:'Flower',ms:'Bunga',icon:'🌸',short:'Struktur pembiakan bagi banyak tumbuhan.',summary:{explorer:'Bunga membantu tumbuhan menghasilkan biji benih baru.',discoverer:'Flower mempunyai struktur yang membantu pollination dan pembentukan seed.',investigator:'Pollination memindahkan pollen ke reproductive structures, kemudian fertilization membolehkan embryo dan seed terbentuk.'},facts:[['🐝','Pollination','Boleh dibantu serangga, angin atau haiwan lain.'],['🌱','Seed','Bunga boleh menghasilkan seed selepas fertilization.'],['🎨','Warna & bau','Boleh menarik pollinator.']]},
    tree:{world:'plants',name:'Tree',ms:'Pokok',icon:'🌳',short:'Tumbuhan berkayu yang boleh hidup bertahun-tahun.',summary:{explorer:'Pokok mempunyai akar, batang, dahan dan daun.',discoverer:'Batang berkayu menyokong pokok dan membawa air serta gula antara akar dan daun.',investigator:'Xylem membawa water/mineral upward, manakala phloem mengangkut sugars dan bahan organik antara source dan sink.'},facts:[['🪵','Batang','Memberi sokongan.'],['💧','Xylem','Membawa air.'],['🍬','Phloem','Membawa hasil photosynthesis.']]},
    photosynthesis:{world:'plants',name:'Photosynthesis',ms:'Fotosintesis',icon:'☀️',short:'Cara tumbuhan menggunakan cahaya untuk menghasilkan gula.',summary:{explorer:'Tumbuhan guna cahaya, air dan udara untuk membuat makanan.',discoverer:'Photosynthesis menggunakan carbon dioxide dan water dengan tenaga cahaya untuk menghasilkan glucose dan oxygen.',investigator:'Photosynthetic reactions dalam chloroplast menukar light energy kepada chemical energy; overall process membina carbohydrate daripada CO₂ dan H₂O.'},facts:[['☀️','Light','Sumber tenaga.'],['💨','CO₂','Masuk melalui stomata.'],['💧','Water','Datang dari akar.'],['🍬','Glucose','Chemical energy untuk tumbuhan.']]},

    heart:{world:'body',name:'Heart',ms:'Jantung',icon:'❤️',short:'Pam otot yang mengalirkan darah ke seluruh badan.',summary:{explorer:'Jantung berdegup untuk menolak darah ke seluruh badan.',discoverer:'Jantung mempunyai empat ruang dan mengepam darah ke paru-paru serta seluruh badan.',investigator:'Cardiac muscle contracts rhythmically; valves memastikan aliran sehala dalam pulmonary dan systemic circulation.'},facts:[['💓','Pam','Menggerakkan darah.'],['4️⃣','Empat ruang','Dua atria dan dua ventricles.'],['🩸','Darah','Membawa oxygen dan nutrients.']]},
    lungs:{world:'body',name:'Lungs',ms:'Paru-paru',icon:'🫁',short:'Organ pertukaran gas untuk mengambil oxygen dan membuang carbon dioxide.',summary:{explorer:'Paru-paru membantu kita bernafas.',discoverer:'Dalam paru-paru, oxygen masuk ke darah dan carbon dioxide keluar.',investigator:'Gas exchange berlaku di alveoli melalui diffusion merentasi membrane nipis antara air sacs dan capillaries.'},facts:[['💨','Oxygen masuk','Digunakan oleh sel badan.'],['↩️','CO₂ keluar','Hasil metabolism dibuang.'],['🫧','Alveoli','Air sacs kecil untuk gas exchange.']]},
    brain:{world:'body',name:'Brain',ms:'Otak',icon:'🧠',short:'Pusat kawalan sistem saraf.',summary:{explorer:'Otak membantu kita berfikir, bergerak, ingat dan rasa.',discoverer:'Otak menerima information daripada deria dan menghantar arahan melalui nervous system.',investigator:'Neural networks memproses sensory input, motor control, memory, language dan fungsi autonomic melalui bahagian otak yang saling berhubung.'},facts:[['⚡','Signals','Neuron berkomunikasi melalui electrical dan chemical signals.'],['👀','Deria','Otak mentafsir input sensory.'],['🧠','Memory','Membantu menyimpan dan recall information.']]},
    bones:{world:'body',name:'Bones',ms:'Tulang',icon:'🦴',short:'Rangka keras yang menyokong dan melindungi badan.',summary:{explorer:'Tulang memberi bentuk pada badan dan melindungi organ.',discoverer:'Skeleton bekerja dengan muscles dan joints untuk membolehkan pergerakan.',investigator:'Bone ialah living tissue yang sentiasa remodel. Marrow dalam sesetengah tulang menghasilkan blood cells.'},facts:[['🛡️','Protection','Skull dan rib cage melindungi organ.'],['🏃','Movement','Muscle menarik tulang di joints.'],['🩸','Marrow','Menghasilkan blood cells.']]},
    stomach:{world:'body',name:'Stomach',ms:'Perut',icon:'🍽️',short:'Organ pencernaan yang mencampurkan makanan dengan acid dan enzymes.',summary:{explorer:'Makanan masuk ke perut untuk dihancur dan dicampur.',discoverer:'Stomach menggunakan muscular movement, acid dan enzymes untuk memulakan digestion protein.',investigator:'Gastric acid menyediakan pH rendah, manakala protease dan mixing menghasilkan chyme sebelum masuk small intestine.'},facts:[['🌀','Mixing','Otot mencampurkan makanan.'],['🧪','Acid','Membantu digestion dan kawal microbes.'],['➡️','Ke usus','Makanan bergerak seterusnya ke small intestine.']]},
    senses:{world:'body',name:'Five Senses',ms:'Lima Deria',icon:'👀',short:'Cara badan mengesan cahaya, bunyi, bau, rasa dan sentuhan.',summary:{explorer:'Mata melihat, telinga mendengar, hidung menghidu, lidah merasa dan kulit menyentuh.',discoverer:'Sensory receptors menukar rangsangan daripada persekitaran kepada signals untuk otak.',investigator:'Transduction converts physical/chemical stimuli into neural signals yang kemudian diproses dalam sensory pathways.'},facts:[['👀','Sight','Cahaya.'],['👂','Hearing','Getaran bunyi.'],['👃','Smell','Molecules dalam udara.'],['👅','Taste','Chemicals dalam makanan.'],['✋','Touch','Pressure, temperature dan pain.']]},

    'traffic-light':{world:'machines',name:'Traffic Light',ms:'Lampu Isyarat',icon:'🚦',short:'Sistem signal yang mengawal giliran trafik.',summary:{explorer:'Merah berhenti, hijau jalan. Lampu isyarat membantu semua orang bergerak dengan selamat.',discoverer:'Controller menukar signal mengikut timing atau data sensor supaya aliran trafik lebih teratur.',investigator:'Traffic signal controllers menggunakan timing plans, detector input dan coordination logic untuk mengurus conflicts antara movement.'},facts:[['🔴','Merah','Berhenti.'],['🟡','Kuning','Bersedia / caution.'],['🟢','Hijau','Boleh bergerak jika selamat.']]},
    fan:{world:'machines',name:'Fan',ms:'Kipas',icon:'🌀',short:'Motor memusingkan blade untuk menggerakkan udara.',summary:{explorer:'Motor memusingkan bilah kipas dan udara pun bergerak.',discoverer:'Electric motor menukar electrical energy menjadi rotation pada blades.',investigator:'Motor menghasilkan torque pada rotor. Blade geometry mempercepatkan udara dan menghasilkan airflow.'},facts:[['⚡','Electricity','Memberi tenaga.'],['🔄','Motor','Menghasilkan putaran.'],['💨','Blade','Menolak udara.']]},
    elevator:{world:'machines',name:'Elevator',ms:'Lif',icon:'🛗',short:'Platform yang bergerak menegak untuk membawa orang atau barang.',summary:{explorer:'Lif naik dan turun dalam bangunan menggunakan motor.',discoverer:'Banyak elevator menggunakan cable, pulley dan counterweight supaya motor tidak perlu mengangkat seluruh berat sendiri.',investigator:'Traction elevators balance car mass with counterweight melalui sheave, mengurangkan energy requirement dan meningkatkan control.'},facts:[['⚙️','Motor','Menggerakkan sistem.'],['🪢','Cable','Menyokong dan menarik car.'],['⚖️','Counterweight','Membantu balance beban.']]},
    electricity:{world:'machines',name:'Electricity',ms:'Elektrik',icon:'⚡',short:'Pergerakan charge yang membolehkan peralatan menerima tenaga.',summary:{explorer:'Elektrik memberi tenaga kepada lampu dan banyak peralatan.',discoverer:'Dalam litar tertutup, electric current boleh mengalir melalui conductor untuk memindahkan energy.',investigator:'Voltage menyediakan potential difference, current ialah rate of charge flow dan resistance mempengaruhi hubungan antara kedua-duanya.'},facts:[['🔋','Source','Battery atau grid memberi electrical energy.'],['🔁','Circuit','Laluan perlu lengkap untuk current mengalir.'],['⚠️','Safety','Elektrik mains berbahaya dan tidak boleh disentuh atau dieksperimen tanpa pengawasan pakar.']]},

    continents:{world:'world',name:'Continents',ms:'Benua',icon:'🌍',short:'Kawasan daratan besar di Bumi.',summary:{explorer:'Bumi mempunyai tujuh benua utama.',discoverer:'Benua ialah kawasan daratan yang sangat besar, biasanya dibahagi kepada Africa, Antarctica, Asia, Europe, North America, South America dan Australia/Oceania.',investigator:'Continental boundaries melibatkan convention geografi dan sejarah; tectonic plates tidak sama sepenuhnya dengan pembahagian benua.'},facts:[['7️⃣','Tujuh','Pembahagian yang biasa digunakan.'],['🌏','Asia','Benua terbesar mengikut keluasan.'],['🧊','Antarctica','Benua paling sejuk.']]},
    malaysia:{world:'world',name:'Malaysia',ms:'Malaysia',icon:'🇲🇾',short:'Negara Asia Tenggara yang terdiri daripada Semenanjung dan Malaysia Timur.',summary:{explorer:'Malaysia ialah negara kita dan mempunyai banyak budaya, makanan serta alam semula jadi.',discoverer:'Malaysia terletak di Asia Tenggara dan mempunyai wilayah di Semenanjung serta Borneo.',investigator:'Malaysia ialah negara persekutuan dengan 13 negeri dan 3 wilayah persekutuan, dipisahkan Laut China Selatan kepada dua kawasan utama.'},facts:[['🏙️','Kuala Lumpur','Ibu negara.'],['🏛️','Putrajaya','Pusat pentadbiran persekutuan.'],['🌴','Biodiversity','Mempunyai hutan tropika yang kaya.']]},
    japan:{world:'world',name:'Japan',ms:'Jepun',icon:'🇯🇵',short:'Negara kepulauan di Asia Timur.',summary:{explorer:'Jepun ialah negara kepulauan dengan bandar moden dan budaya yang panjang.',discoverer:'Japan terdiri daripada ribuan pulau, dengan Honshu, Hokkaido, Kyushu dan Shikoku antara pulau utama.',investigator:'Japan berada berhampiran beberapa plate boundaries, sebab itu gempa bumi dan volcanism agak aktif.'},facts:[['🗼','Tokyo','Ibu negara.'],['🗻','Mount Fuji','Gunung berapi ikonik.'],['🚄','Shinkansen','High-speed rail terkenal.']]},
    egypt:{world:'world',name:'Egypt',ms:'Mesir',icon:'🇪🇬',short:'Negara di Afrika Utara yang terkenal dengan Nile dan tamadun purba.',summary:{explorer:'Mesir terkenal dengan piramid dan Sungai Nile.',discoverer:'Nile sangat penting kepada sejarah Mesir kerana kawasan subur terbentuk di sepanjang sungai.',investigator:'Ancient Egyptian civilization berkembang selama ribuan tahun, dengan agriculture, writing, architecture dan state organization yang kompleks.'},facts:[['🔺','Pyramids','Monumen purba terkenal.'],['🏞️','Nile','Sungai penting kepada kehidupan dan agriculture.'],['🏺','Ancient Egypt','Tamadun yang sangat berpengaruh.']]},
    flags:{world:'world',name:'Flags',ms:'Bendera',icon:'🏳️',short:'Simbol visual yang mewakili negara atau kumpulan.',summary:{explorer:'Setiap negara mempunyai bendera dengan warna dan simbol tersendiri.',discoverer:'Flags menggunakan design ringkas supaya mudah dikenali dari jauh.',investigator:'Vexillology ialah kajian tentang flags; symbolism warna dan bentuk banyak dipengaruhi sejarah, culture dan politics.'},facts:[['🎨','Warna','Selalunya ada makna simbolik.'],['🔷','Bentuk','Pattern membantu pengenalan.'],['🏳️','Identity','Boleh mewakili negara, organisasi atau komuniti.']]},

    gravity:{world:'science',name:'Gravity',ms:'Graviti',icon:'🍎',short:'Daya tarikan antara objek yang mempunyai jisim.',summary:{explorer:'Graviti menarik benda ke arah Bumi, sebab itu kita tidak terapung.',discoverer:'Semua objek yang mempunyai mass menarik antara satu sama lain, tetapi tarikan Bumi paling jelas kepada kita.',investigator:'Dalam model Newton, gravitational force bergantung pada mass dan jarak. General relativity menerangkan gravity sebagai curvature spacetime.'},facts:[['⬇️','Tarik ke bawah','Dekat Bumi, kita rasa tarikan ke pusat Bumi.'],['🌙','Orbit','Gravity membantu mengekalkan Moon dalam orbit.'],['🪐','Universal','Semua mass mempunyai gravitational interaction.']]},
    magnet:{world:'science',name:'Magnet',ms:'Magnet',icon:'🧲',short:'Objek yang menghasilkan magnetic field.',summary:{explorer:'Magnet boleh menarik sesetengah logam seperti besi.',discoverer:'Magnet mempunyai kutub north dan south. Kutub sama menolak, kutub berbeza menarik.',investigator:'Magnetic fields terhasil daripada moving charges dan magnetic moments. Ferromagnetic materials boleh membentuk domains yang aligned.'},facts:[['N/S','Dua kutub','North dan South.'],['↔️','Tarik/tolak','Bergantung pada orientasi kutub.'],['🧭','Compass','Jarum magnet sejajar dengan medan magnet Bumi.']]},
    light:{world:'science',name:'Light',ms:'Cahaya',icon:'💡',short:'Electromagnetic radiation yang boleh dilihat oleh mata.',summary:{explorer:'Cahaya membolehkan kita melihat benda.',discoverer:'Kita melihat apabila light dari source dipantulkan objek dan masuk ke mata.',investigator:'Visible light ialah sebahagian electromagnetic spectrum. Reflection, refraction, absorption dan scattering menentukan interaksinya dengan matter.'},facts:[['👀','Vision','Mata mengesan visible light.'],['🪞','Reflection','Cahaya boleh dipantulkan.'],['🌈','Spectrum','White light boleh dipisahkan kepada warna.']]},
    sound:{world:'science',name:'Sound',ms:'Bunyi',icon:'🔊',short:'Gelombang mekanikal daripada getaran.',summary:{explorer:'Bunyi bermula apabila sesuatu bergetar.',discoverer:'Vibration menghasilkan pressure waves yang bergerak melalui udara, air atau bahan lain.',investigator:'Sound memerlukan medium. Frequency berkait dengan pitch dan amplitude berkait dengan sound pressure/intensity.'},facts:[['〰️','Wave','Bunyi bergerak sebagai perubahan pressure.'],['🎵','Frequency','Mempengaruhi pitch.'],['📢','Amplitude','Mempengaruhi kuat bunyi.']]},
    states:{world:'science',name:'States of Matter',ms:'Keadaan Jirim',icon:'🧊',short:'Solid, liquid dan gas ialah bentuk biasa matter.',summary:{explorer:'Ais ialah solid, air ialah liquid dan wap ialah gas.',discoverer:'Heating atau cooling boleh mengubah state apabila particles mendapat atau kehilangan energy.',investigator:'Phase changes berlaku apabila thermodynamic conditions mengubah organization dan energy molecular system.'},facts:[['🧊','Solid','Bentuk dan isipadu lebih tetap.'],['💧','Liquid','Isipadu tetap tetapi ikut bentuk bekas.'],['💨','Gas','Mengembang memenuhi ruang.']]},

    satellite:{world:'technology',name:'Satellite',ms:'Satelit',icon:'🛰️',short:'Objek yang mengorbit planet atau badan lain.',summary:{explorer:'Satelit buatan boleh melihat Bumi, membantu GPS dan menghantar signal.',discoverer:'Satellites menggunakan orbit berbeza untuk communication, weather, navigation dan science.',investigator:'Orbital altitude dan inclination dipilih mengikut mission. Communication links bergantung pada frequency, antenna gain dan link budget.'},facts:[['📡','Communication','Menghubungkan lokasi yang jauh.'],['🗺️','Navigation','GNSS membantu menentukan position.'],['🌦️','Weather','Mengamati cloud dan atmosphere.']]},
    internet:{world:'technology',name:'Internet',ms:'Internet',icon:'🌐',short:'Rangkaian besar yang menghubungkan banyak rangkaian komputer.',summary:{explorer:'Internet membolehkan device menghantar maklumat antara satu sama lain.',discoverer:'Data dipecahkan kepada packets dan melalui routers sebelum sampai ke destination.',investigator:'Internet menggunakan layered protocols seperti IP, TCP/UDP, DNS dan application protocols. Routing systems menentukan path antara networks.'},facts:[['📦','Packets','Data dihantar dalam bahagian kecil.'],['🛣️','Routers','Mengarahkan traffic.'],['🔤','DNS','Membantu menukar nama domain kepada address.']]},
    robot:{world:'technology',name:'Robot',ms:'Robot',icon:'🤖',short:'Mesin yang boleh sense, process dan act.',summary:{explorer:'Robot menggunakan sensor untuk tahu apa berlaku dan motor untuk bergerak.',discoverer:'Robot biasanya menggabungkan sensors, controller/software dan actuators.',investigator:'Robotics menggabungkan perception, planning/control dan actuation. Autonomy bergantung pada algorithms serta feedback daripada sensors.'},facts:[['👀','Sensors','Mengesan dunia.'],['🧠','Controller','Memproses information.'],['💪','Actuator','Menghasilkan movement.']]},
    computer:{world:'technology',name:'Computer',ms:'Komputer',icon:'💻',short:'Mesin yang memproses data mengikut arahan.',summary:{explorer:'Komputer ikut arahan untuk mengira, menyimpan dan memaparkan maklumat.',discoverer:'CPU memproses instructions, memory menyimpan data sementara dan storage menyimpan fail.',investigator:'A computer system menggabungkan hardware dan software. CPU executes machine instructions while operating systems manage resources and applications.'},facts:[['🧠','CPU','Memproses instructions.'],['🧮','Memory','Menyimpan data semasa digunakan.'],['💾','Storage','Menyimpan data lebih lama.']]},

    'english-first-words':{world:'english',name:'My First Words',ms:'Perkataan Pertama',icon:'🔤',short:'Belajar perkataan biasa dengan gambar, bunyi dan ayat.',mode:'vocab',vocab:[['🍎','apple','epal','This is an apple.'],['🐶','dog','anjing','The dog is happy.'],['☀️','sun','matahari','The sun is bright.'],['🏠','house','rumah','This is my house.'],['📘','book','buku','I read a book.'],['⚽','ball','bola','The ball is round.'],['🚗','car','kereta','The car is red.'],['🌳','tree','pokok','The tree is tall.']]},
    'english-home':{world:'english',name:'At Home',ms:'Di Rumah',icon:'🏠',short:'Vocabulary benda yang selalu kita nampak di rumah.',mode:'vocab',vocab:[['🚪','door','pintu','Open the door, please.'],['🪟','window','tingkap','The window is open.'],['🛏️','bed','katil','I sleep on my bed.'],['💡','lamp','lampu','Turn on the lamp.'],['🪑','chair','kerusi','Sit on the chair.'],['🧸','teddy bear','patung beruang','My teddy bear is soft.'],['🧊','fridge','peti sejuk','The milk is in the fridge.'],['🚿','shower','pancuran','I take a shower.']]},
    'english-animals':{world:'english',name:'Animals',ms:'Haiwan',icon:'🐾',short:'Belajar nama haiwan dan perkataan untuk menerangkannya.',mode:'vocab',vocab:[['🦁','lion','singa','The lion is strong.'],['🐘','elephant','gajah','The elephant has big ears.'],['🦒','giraffe','zirafah','The giraffe has a long neck.'],['🐯','tiger','harimau','The tiger has stripes.'],['🐬','dolphin','ikan lumba-lumba','The dolphin can swim.'],['🦅','eagle','helang','The eagle can fly.'],['🐧','penguin','penguin','The penguin walks on ice.'],['🐢','turtle','kura-kura','The turtle has a shell.']]},
    'english-food':{world:'english',name:'Food & Drinks',ms:'Makanan & Minuman',icon:'🍓',short:'Perkataan mudah untuk makanan, rasa dan cara meminta makanan.',mode:'vocab',vocab:[['🍚','rice','nasi','I eat rice.'],['🍞','bread','roti','I like bread.'],['🥛','milk','susu','I drink milk.'],['💧','water','air','Can I have some water?'],['🍌','banana','pisang','The banana is yellow.'],['🍓','strawberry','strawberi','The strawberry is sweet.'],['🥚','egg','telur','I eat an egg for breakfast.'],['🥕','carrot','lobak merah','The carrot is crunchy.']]},
    'english-actions':{world:'english',name:'Actions',ms:'Perbuatan',icon:'🏃',short:'Learn verbs by seeing the action in a sentence.',mode:'vocab',vocab:[['🏃','run','berlari','I can run fast.'],['🦘','jump','melompat','Jump over the line.'],['🪑','sit','duduk','Please sit down.'],['🚶','walk','berjalan','We walk to the park.'],['🍴','eat','makan','I eat an apple.'],['🥤','drink','minum','I drink water.'],['📖','read','membaca','I read a story.'],['✍️','write','menulis','I write my name.']]},
    'english-feelings':{world:'english',name:'Feelings',ms:'Perasaan',icon:'😊',short:'Cara cakap apa yang kita rasa.',mode:'vocab',vocab:[['😊','happy','gembira','I am happy.'],['😢','sad','sedih','She feels sad.'],['😠','angry','marah','He is angry.'],['😴','tired','penat','I am tired.'],['🤩','excited','teruja','We are excited!'],['😨','scared','takut','The child is scared.'],['😌','calm','tenang','Take a breath and stay calm.'],['🤔','confused','keliru','I am confused.']]},
    'english-body':{world:'english',name:'Body Parts',ms:'Anggota Badan',icon:'🧍',short:'Vocabulary badan dan ayat mudah.',mode:'vocab',vocab:[['👀','eyes','mata','I see with my eyes.'],['👂','ears','telinga','I hear with my ears.'],['👃','nose','hidung','I smell with my nose.'],['👄','mouth','mulut','Open your mouth.'],['✋','hand','tangan','Raise your hand.'],['🦶','foot','kaki','My foot is on the floor.'],['🦵','leg','kaki','I bend my leg.'],['💪','arm','lengan','Lift your arm.']]},
    'english-colors':{world:'english',name:'Colours & Shapes',ms:'Warna & Bentuk',icon:'🎨',short:'Belajar warna dan bentuk melalui benda di sekeliling.',mode:'vocab',vocab:[['🔴','red','merah','The ball is red.'],['🔵','blue','biru','The sky is blue.'],['🟢','green','hijau','The leaf is green.'],['🟡','yellow','kuning','The banana is yellow.'],['⚪','circle','bulatan','This is a circle.'],['🔺','triangle','segi tiga','This is a triangle.'],['⬛','square','segi empat sama','This is a square.'],['⭐','star','bintang','Draw a star.']]},
    'sentence-builder':{world:'english',name:'Sentence Builder',ms:'Bina Ayat',icon:'🧩',short:'Susun perkataan menjadi ayat yang betul.',mode:'sentence',sentences:[['The','girl','eats','an','apple.'],['The','dog','runs','in','the','park.'],['I','drink','water','every','day.'],['The','blue','car','is','fast.']]},
    conversation:{world:'english',name:'Everyday Conversation',ms:'Perbualan Harian',icon:'💬',short:'Belajar ayat yang kita guna dalam situasi sebenar.',mode:'conversation',scenes:[{place:'🍽️ Restaurant',lines:[['👩‍🍳','Hello! What would you like?'],['🧒','I would like some juice, please.'],['👩‍🍳','Here you are.'],['🧒','Thank you!']]},{place:'🏫 School',lines:[['👩‍🏫','Good morning!'],['🧒','Good morning, teacher!'],['👩‍🏫','How are you today?'],['🧒','I am great, thank you.']]}]},
    'mini-story':{world:'english',name:'Mini Stories',ms:'Cerita Pendek',icon:'📖',short:'Baca ayat pendek dan tekan perkataan untuk dengar.',mode:'story',story:'Tom has a red ball. Tom throws the ball. The dog runs after it. The dog brings the ball back. Tom is happy.'},
    'word-hunt':{world:'english',name:'Word Hunt',ms:'Cari Perkataan',icon:'🔎',short:'Cari objek berdasarkan arahan English.',mode:'hunt',hunt:[['🛏️','bed'],['🪟','window'],['💡','lamp'],['🚪','door'],['🧸','teddy bear'],['🪑','chair']]}
  }
};

// Fill a few category placeholders with lightweight but usable content.
const placeholders = {
  seed:['plants','Seed','Biji Benih','🌰'], roots:['plants','Roots','Akar','🪴'], leaf:['plants','Leaf','Daun','🍃'], flower:['plants','Flower','Bunga','🌸'], tree:['plants','Tree','Pokok','🌳'], photosynthesis:['plants','Photosynthesis','Fotosintesis','☀️'],
};

// Friendly fallback topics for entries not yet expanded in v1.
Object.values(TEROKA_DATA.worlds).forEach(world=>{
  world.topics.forEach(id=>{
    if(!TEROKA_DATA.topics[id]){
      const label=id.replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
      TEROKA_DATA.topics[id]={world:world.id,name:label,ms:label,icon:world.icon,short:'Topik penerokaan ini tersedia sebagai starter lesson dalam TerokaKu v1.',summary:{explorer:`Jom kenali ${label} melalui gambar dan penerangan mudah.`,discoverer:`Teroka asas ${label}, ciri penting dan bagaimana ia berkait dengan dunia di sekeliling kita.`,investigator:`Starter lesson ${label} menyediakan gambaran konsep utama dan akan diperluas sebagai content pack seterusnya.`},facts:[['✨','Kenali','Lihat ciri utama topik ini.'],['🔎','Teroka','Cari perkara yang membezakannya.'],['🧠','Fahami','Hubungkan konsep dengan contoh sebenar.']]};
    }
  });
});
