const S=(icon,title,lead,detail,bullets=[],investigator='')=>({icon,title,lead,detail,bullets,investigator});
const DEEP_CONTENT={
  'solar-system':[
    S('🌌','Apa sebenarnya Sistem Suria?','Sistem Suria bukan sekadar lapan planet. Ia ialah seluruh kawasan yang dikuasai graviti Matahari.','Di dalamnya ada Matahari, planet, dwarf planet, ratusan bulan, asteroid, komet, debu dan objek berais yang semuanya bergerak mengikut orbit.', ['Matahari menyimpan lebih 99% jisim Sistem Suria.','Planet berbatu berada lebih dekat dengan Matahari; giant planets berada lebih jauh.','Sistem Suria berada dalam galaksi Milky Way.']),
    S('🌀','Bagaimana semuanya bermula?','Kira-kira 4.6 bilion tahun lalu, awan gas dan debu runtuh lalu membentuk cakera yang berpusing.','Bahan paling banyak berkumpul di tengah lalu menjadi Matahari. Baki bahan bercantum sedikit demi sedikit menjadi planet, moon, asteroid dan objek kecil lain.', ['Proses ini mengambil masa berjuta-juta tahun.','Bahan dekat Matahari lebih sesuai membentuk planet berbatu.','Bahan berais lebih mudah kekal di kawasan yang jauh dan sejuk.']),
    S('🧲','Kenapa planet kekal dalam orbit?','Graviti Matahari menarik planet ke dalam, tetapi planet pada masa sama bergerak ke hadapan.','Gabungan tarikan graviti dan gerakan ke hadapan menghasilkan orbit. Tanpa gerakan ke hadapan, planet akan jatuh ke Matahari; tanpa graviti, planet akan bergerak keluar.', ['Orbit bukan bulatan sempurna; kebanyakannya berbentuk ellipse.','Planet yang lebih dekat biasanya mengambil masa lebih singkat untuk mengelilingi Matahari.']),
    S('🪨','Rocky planet vs giant planet','Mercury, Venus, Earth dan Mars mempunyai permukaan pepejal. Jupiter dan Saturn ialah gas giants, manakala Uranus dan Neptune ialah ice giants.','Perbezaan ini datang daripada bahan asal, suhu kawasan pembentukan dan jumlah gas yang dapat dikumpulkan oleh setiap planet.', ['Rocky planets: kecil tetapi lebih padat.','Giant planets: sangat besar, banyak gas dan mempunyai banyak moon.']),
    S('☄️','Apa lagi yang ada di luar planet?','Asteroid ialah objek berbatu atau logam; komet pula kaya dengan ais dan debu.','Banyak asteroid berada di asteroid belt antara Mars dan Jupiter. Komet boleh datang dari kawasan sangat jauh dan membentuk ekor apabila menghampiri Matahari.', ['Dwarf planet seperti Pluto mengorbit Matahari tetapi belum “membersihkan” kawasan orbitnya.','Kuiper Belt berada di luar Neptune.']),
    S('🚀','Bagaimana manusia mengkajinya?','Kita gunakan telescope, spacecraft, lander dan rover.','Spacecraft boleh fly-by, masuk orbit, mendarat atau menghantar rover. Setiap jenis misi menjawab soalan berbeza tentang atmosphere, permukaan, medan magnet dan sejarah planet.', ['Voyager mengkaji outer planets.','Rover seperti Curiosity dan Perseverance mengkaji Mars.','Telescope mengesan objek tanpa perlu pergi ke sana.']),
  ],
  sun:[
    S('⭐','Matahari ialah bintang','Matahari nampak lebih besar daripada bintang lain kerana ia jauh lebih dekat kepada Bumi.','Ia ialah bebola plasma yang sangat besar, kebanyakannya hidrogen dan helium. Matahari bukan api seperti unggun; ia menghasilkan tenaga melalui nuclear fusion.', ['Umur Matahari kira-kira 4.6 bilion tahun.','Diameter lebih kurang 1.39 juta km.','Bumi berada kira-kira 150 juta km daripadanya.']),
    S('⚛️','Bagaimana Matahari menghasilkan tenaga?','Di core, tekanan dan suhu sangat tinggi sehingga hydrogen nuclei boleh bergabung menjadi helium.','Proses nuclear fusion ini melepaskan tenaga. Tenaga itu bergerak keluar melalui bahagian dalam Matahari sebelum akhirnya dilepaskan sebagai cahaya dan haba.', ['Core boleh mencecah sekitar 15 juta °C.','Fusion menukar sedikit jisim kepada tenaga.','Inilah sumber utama cahaya Matahari.'], 'Pada tahap lebih tinggi: hubungan jisim-tenaga sering diringkaskan dengan E = mc².'),
    S('🧅','Lapisan-lapisan Matahari','Matahari mempunyai struktur berlapis, bukan satu bebola seragam.','Dari dalam ke luar: core → radiative zone → convection zone → photosphere → chromosphere → corona. Setiap lapisan memindahkan atau melepaskan tenaga dengan cara berbeza.', ['Photosphere ialah “permukaan” yang kita nampak, sekitar 5,500°C.','Convection zone membawa plasma panas naik dan plasma lebih sejuk turun.','Corona ialah atmosphere luar yang sangat panas.']),
    S('⏳','Perjalanan tenaga dari core ke Bumi','Cahaya yang kita lihat hari ini bermula sebagai tenaga di core jauh lebih awal.','Tenaga boleh mengambil masa sangat lama untuk merentas radiative zone kerana photon sentiasa diserap dan dipancarkan semula. Selepas meninggalkan permukaan, cahaya mengambil kira-kira 8 minit 20 saat untuk sampai ke Bumi.', ['Perjalanan dalam Matahari: sangat lambat.','Perjalanan melalui ruang kosong ke Bumi: sangat pantas.']),
    S('🧲','Sunspot, flare dan solar wind','Matahari mempunyai medan magnet yang sentiasa berubah.','Kawasan magnet kuat boleh menghasilkan sunspot, solar flare dan coronal mass ejection. Matahari juga menghembuskan aliran zarah yang dipanggil solar wind.', ['Solar activity boleh menghasilkan aurora di Bumi.','Gangguan kuat boleh menjejaskan satellite, radio dan power grid.','Sunspot nampak gelap kerana lebih sejuk daripada kawasan sekeliling.']),
    S('🌱','Kenapa Matahari penting kepada kehidupan?','Hampir semua tenaga yang menggerakkan ekosistem Bumi bermula daripada Matahari.','Tumbuhan menggunakan cahaya untuk photosynthesis. Matahari juga memacu water cycle, cuaca dan perbezaan suhu antara kawasan di Bumi.', ['Tanpa Matahari, Bumi akan menjadi sangat sejuk.','Jarak Bumi daripada Matahari membantu air kekal sebagai cecair.']),
    S('🕶️','Keselamatan & masa depan Matahari','Jangan tengok Matahari secara terus tanpa solar filter yang betul.','Matahari masih berada pada fasa stabil untuk berbilion tahun lagi. Apabila hidrogen core semakin berkurang, ia akhirnya akan berubah menjadi red giant sebelum meninggalkan white dwarf.', ['Solar eclipse juga memerlukan perlindungan mata yang betul kecuali pada tempoh totality penuh.','Matahari tidak akan “meletup” seperti supernova kerana massanya tidak cukup besar.'])
  ],
  mercury:[
    S('🪨','Dunia berbatu paling kecil','Mercury ialah planet terkecil dan paling dekat dengan Matahari.','Permukaannya penuh crater kerana hampir tiada atmosphere tebal untuk membakar meteoroid atau menghakis kesan hentaman.', ['Tiada moon.','Satu tahun ≈ 88 hari Bumi.','Permukaan menyerupai Moon dalam banyak kawasan.']),
    S('🌡️','Panas siang, sangat sejuk malam','Dekat dengan Matahari tidak bermaksud seluruh planet sentiasa panas.','Atmosphere Mercury terlalu nipis untuk menyimpan dan mengagihkan haba. Bahagian siang boleh sangat panas manakala malam jatuh ke suhu sangat rendah.', ['Venus sebenarnya lebih panas secara purata kerana greenhouse effect kuat.']),
    S('🕰️','Hari yang pelik','Mercury berputar perlahan tetapi mengorbit Matahari dengan cepat.','Gabungan rotation dan revolution menyebabkan satu solar day di Mercury sangat panjang berbanding tahunnya.', ['Rotation ≈ 59 hari Bumi.','Solar day ≈ 176 hari Bumi.']),
    S('🧲','Teras besar & medan magnet','Mercury mempunyai iron core yang sangat besar berbanding saiz planet.','Walaupun kecil, ia mempunyai magnetic field yang lemah tetapi nyata, memberi petunjuk bahawa bahagian core masih aktif.', ['Saintis mengkaji graviti dan medan magnet untuk memahami bahagian dalam planet.']),
    S('🧊','Ais dekat planet paling dekat Matahari?','Ya — ais boleh wujud di crater kutub yang tidak pernah menerima cahaya Matahari.','Bahagian dasar crater tertentu kekal dalam permanent shadow dan sangat sejuk, membolehkan water ice bertahan.', ['Ini menunjukkan lokasi dan cahaya lebih penting daripada sekadar jarak purata ke Matahari.'])
  ],
  venus:[
    S('🌋','Saiz hampir Bumi, keadaan sangat berbeza','Venus hampir sama saiz dengan Bumi tetapi permukaannya sangat ekstrem.','Atmosphere yang tebal dan tekanan tinggi menjadikannya contoh terbaik bagaimana dua planet serupa saiz boleh berkembang sangat berbeza.', ['Banyak kawasan gunung berapi.','Tiada moon.']),
    S('🧣','Greenhouse effect luar biasa','Carbon dioxide yang banyak memerangkap haba dengan sangat kuat.','Cahaya Matahari masuk, permukaan memanaskan, tetapi banyak haba sukar keluar semula. Ini menyebabkan suhu permukaan sekitar 465°C.', ['Venus lebih panas daripada Mercury walaupun lebih jauh dari Matahari.']),
    S('☁️','Awan bukan macam awan Bumi','Awan Venus kaya dengan titisan sulfuric acid.','Awan tebal memantulkan banyak cahaya, sebab itu Venus sangat terang di langit Bumi walaupun permukaannya sendiri tersembunyi.', ['Kita banyak memetakan permukaan menggunakan radar.']),
    S('🔄','Berputar terbalik','Venus berputar dalam arah berlawanan daripada kebanyakan planet.','Jika berdiri di permukaan, Matahari secara umum akan nampak terbit dari barat dan terbenam di timur.', ['Rotation sangat perlahan.','Satu rotation mengambil lebih lama daripada satu Venus year.']),
    S('🛰️','Kenapa Venus penting dikaji?','Venus membantu saintis memahami climate dan atmosphere planet.','Dengan membandingkan Venus, Earth dan Mars, kita belajar bagaimana atmosphere, water dan geologi boleh mengubah masa depan sesebuah planet.', [])
  ],
  earth:[
    S('🌍','Planet aktif','Earth mempunyai atmosphere, ocean, crust yang bergerak dan kehidupan.','Ia bukan sistem yang statik. Atmosphere, ocean, land dan biosphere sentiasa bertukar tenaga dan bahan.', ['71% permukaan diliputi air.','Satu moon.','Plate tectonics mengubah permukaan dari masa ke masa.']),
    S('🧅','Lapisan Bumi','Dari luar ke dalam: crust, mantle, outer core dan inner core.','Crust sangat nipis berbanding saiz Bumi. Mantle yang panas boleh mengalir sangat perlahan; outer core cecair membantu menghasilkan magnetic field.', ['Inner core pepejal walaupun sangat panas kerana tekanan amat tinggi.']),
    S('🌬️','Atmosphere','Atmosphere Bumi kebanyakannya nitrogen dan oxygen.','Ia membantu mengawal suhu, menyediakan gas untuk kehidupan dan membakar banyak meteoroid kecil sebelum sampai ke tanah.', ['Troposphere ialah tempat kebanyakan cuaca berlaku.','Ozone membantu menyerap ultraviolet berbahaya.']),
    S('🧲','Perisai magnet','Pergerakan logam cair dalam outer core membantu menghasilkan magnetic field.','Magnetosphere membelokkan banyak zarah bercas daripada solar wind, walaupun sebahagian zarah boleh menghasilkan aurora dekat kutub.', []),
    S('💧','Water cycle & kehidupan','Air bergerak antara ocean, udara, sungai, tanah dan hidupan.','Evaporation, condensation dan precipitation membentuk water cycle. Air cecair juga sangat penting untuk chemistry kehidupan yang kita kenal.', []),
    S('🌙','Hubungan dengan Moon','Moon mempengaruhi tides dan membantu menstabilkan tilt Bumi dalam jangka masa panjang.','Tides datang terutamanya daripada perbezaan tarikan graviti Moon pada bahagian Bumi yang berbeza.', [])
  ],
  mars:[
    S('🔴','Kenapa Mars merah?','Tanah Mars kaya dengan iron minerals yang telah teroksida.','Proses ini serupa dengan pembentukan karat, lalu memberi warna merah-orennya.', ['Planet berbatu.','Atmosphere sangat nipis, kebanyakannya carbon dioxide.']),
    S('🌋','Gunung dan canyon gergasi','Mars mempunyai Olympus Mons dan Valles Marineris.','Olympus Mons ialah gunung berapi sangat besar; Valles Marineris ialah sistem canyon yang jauh lebih besar daripada Grand Canyon.', []),
    S('💧','Jejak air lama','Mars hari ini sejuk dan kering, tetapi banyak bukti menunjukkan air pernah mengalir di permukaan.','Rover dan orbiter menemui valley, mineral dan batuan yang biasanya terbentuk dengan kehadiran air.', ['Ais air masih wujud terutama di kutub dan bawah permukaan.']),
    S('🌙','Phobos dan Deimos','Mars mempunyai dua moon kecil berbentuk tidak sekata.','Phobos mengorbit sangat dekat dan perlahan-lahan mendekati Mars; pada masa depan yang sangat jauh ia mungkin pecah atau menghentam planet.', []),
    S('🤖','Kenapa banyak robot dihantar ke Mars?','Mars relatif dekat, mempunyai permukaan pepejal dan menyimpan rekod geologi lama.','Rover boleh menganalisis batuan, cuaca dan chemistry untuk mencari petunjuk sama ada Mars pernah sesuai untuk kehidupan mikrob.', [])
  ],
  jupiter:[
    S('🏆','Planet terbesar','Jupiter sangat besar sehingga lebih 1,300 Bumi boleh muat dari segi volume secara kasar.','Ia kebanyakannya hydrogen dan helium dan tidak mempunyai permukaan pepejal seperti Earth.', ['Gas giant.','Putaran sangat cepat — satu hari kira-kira 10 jam.']),
    S('🌪️','Great Red Spot','Great Red Spot ialah ribut gergasi dalam atmosphere Jupiter.','Ribut ini telah diperhatikan selama berabad-abad dan mempunyai angin yang sangat kuat. Saiznya berubah dari masa ke masa.', []),
    S('🧅','Apa ada di dalam Jupiter?','Semakin masuk ke dalam, tekanan meningkat sehingga hydrogen berubah sifat.','Saintis fikir terdapat lapisan molecular hydrogen, metallic hydrogen dan core yang mungkin tersebar atau tidak mempunyai sempadan tajam.', ['Metallic hydrogen boleh mengalirkan elektrik.']),
    S('🧲','Magnetic field sangat kuat','Jupiter mempunyai magnetosphere yang sangat besar.','Rotation pantas dan bahan pengalir di bahagian dalam membantu menghasilkan magnetic field kuat serta radiation belts berbahaya untuk spacecraft.', []),
    S('🌙','Dunia kecil di sekeliling Jupiter','Empat moon terbesar — Io, Europa, Ganymede dan Callisto — sangat berbeza antara satu sama lain.','Io sangat volcanic, Europa dipercayai mempunyai ocean bawah ais, Ganymede ialah moon terbesar, dan Callisto penuh crater.', [])
  ],
  saturn:[
    S('🪐','Planet dengan sistem cincin paling jelas','Saturn ialah gas giant yang kebanyakannya hydrogen dan helium.','Cincinnya kelihatan seperti cakera, tetapi sebenarnya terdiri daripada berjuta-juta hingga berbilion ketulan ais dan batu yang mengorbit secara berasingan.', ['Planet ke-6 dari Matahari.','Sangat besar tetapi kurang padat.']),
    S('💍','Bagaimana cincin tersusun?','Cincin mempunyai banyak ringlet dan gap.','Zarah lebih dekat bergerak lebih cepat daripada zarah lebih jauh kerana hukum orbit. Gravity moon tertentu membantu membentuk edge dan gap.', ['Cincin sangat lebar tetapi relatif nipis.']),
    S('🌫️','Tiada permukaan pepejal','Jika turun ke Saturn, kita tidak akan jumpa tanah untuk berdiri.','Gas menjadi semakin padat apabila tekanan meningkat. Lebih dalam, hydrogen boleh berubah kepada bentuk metallic hydrogen.', []),
    S('🌙','Titan dan moon lain','Titan ialah moon besar dengan atmosphere tebal dan tasik hydrocarbon di permukaan.','Enceladus pula menyemburkan plume ais dan wap air dari bawah permukaan, menjadikannya sasaran penting dalam pencarian habitat yang mungkin sesuai untuk kehidupan.', []),
    S('🌀','Cuaca pelik','Saturn mempunyai angin sangat laju dan bentuk hexagon besar dekat kutub utara.','Hexagon itu ialah corak aliran atmosphere yang stabil, bukan struktur pepejal.', [])
  ],
  uranus:[
    S('🩵','Ice giant','Uranus mengandungi hydrogen, helium dan lebih banyak bahan “ice” seperti water, ammonia dan methane berbanding gas giants.','Methane menyerap cahaya merah dan membantu memberi warna biru-hijau.', []),
    S('↔️','Planet yang “baring”','Axis Uranus condong sekitar 98°, jadi ia berputar hampir mengiring.','Ini mungkin akibat perlanggaran besar pada awal sejarah planet atau gabungan interaksi graviti kompleks.', []),
    S('🌦️','Musim sangat ekstrem','Disebabkan tilt besar dan orbit yang panjang, setiap kutub boleh menghadap Matahari untuk tempoh yang sangat lama.','Satu tahun Uranus mengambil kira-kira 84 tahun Bumi.', []),
    S('💍','Ada cincin juga','Uranus mempunyai sistem cincin gelap dan sempit.','Cincin itu jauh kurang terang berbanding Saturn, sebab itu ia sukar dilihat tanpa instrument yang sesuai.', []),
    S('🛰️','Masih misteri','Voyager 2 ialah satu-satunya spacecraft yang pernah fly-by Uranus dari dekat.','Banyak perkara tentang interior, moon dan cuacanya masih perlu dikaji dengan misi masa depan.', [])
  ],
  neptune:[
    S('🔵','Planet utama paling jauh','Neptune ialah ice giant yang sangat jauh dan sejuk.','Methane membantu memberi warna kebiruan, tetapi warna sebenar dan chemistry atmosphere lebih kompleks daripada methane sahaja.', []),
    S('💨','Angin sangat laju','Neptune mempunyai antara angin terpantas dalam Sistem Suria.','Walaupun menerima sedikit cahaya Matahari, ia mempunyai cuaca aktif dan mengeluarkan haba dalaman.', []),
    S('🌀','Dark spots','Ribut besar boleh muncul sebagai dark spots dan kemudian hilang.','Ini menunjukkan atmosphere Neptune berubah dengan cepat walaupun planetnya jauh dan sejuk.', []),
    S('🌙','Triton','Triton ialah moon terbesar Neptune dan bergerak pada retrograde orbit.','Orbit pelik ini menunjukkan Triton mungkin objek Kuiper Belt yang ditangkap oleh graviti Neptune.', []),
    S('⏱️','Tahun yang sangat panjang','Satu orbit Neptune mengambil sekitar 165 tahun Bumi.','Sejak ditemui pada 1846, Neptune baru menyelesaikan kira-kira satu orbit penuh pada 2011.', [])
  ],
  moon:[
    S('🌙','Satelit semula jadi Bumi','Moon mengorbit Earth dan sentiasa memantulkan cahaya Matahari.','Moon tidak menghasilkan cahaya sendiri. Bentuk yang kita nampak berubah mengikut bahagian yang diterangi dan posisi Moon relatif kepada Earth dan Sun.', []),
    S('🌓','Kenapa ada phase?','Half Moon, crescent dan full Moon bukan disebabkan bayang Earth kebanyakan masa.','Phase berlaku kerana kita melihat bahagian berbeza daripada half Moon yang disinari Matahari semasa Moon mengorbit Earth.', []),
    S('🌊','Moon dan tides','Gravity Moon menarik bahagian Bumi dengan kekuatan sedikit berbeza.','Perbezaan ini menghasilkan bulges pada ocean dan menyumbang kepada pasang surut. Sun juga mempengaruhi tides.', []),
    S('👣','Permukaan tanpa cuaca biasa','Moon hampir tiada atmosphere, jadi tiada hujan atau angin seperti Earth.','Footprint astronaut boleh kekal sangat lama kerana tiada weather untuk menghakisnya, walaupun micrometeorite masih mengubah permukaan perlahan-lahan.', []),
    S('🔒','Kenapa kita nampak muka yang sama?','Moon tidally locked dengan Earth.','Masa Moon berputar sekali pada axis hampir sama dengan masa ia mengorbit Earth, jadi sisi yang sama sentiasa menghadap kita.', [])
  ],
  rocket:[
    S('🚀','Rocket bergerak dengan action–reaction','Rocket menolak gas panas ke belakang, lalu rocket dipercepatkan ke hadapan.','Ini ialah aplikasi Newton’s third law. Rocket tidak perlu “menolak udara”, sebab itu ia boleh berfungsi dalam vacuum.', []),
    S('🔥','Engine & propellant','Rocket membawa fuel dan oxidizer sendiri.','Pembakaran menghasilkan gas tekanan tinggi yang keluar melalui nozzle pada kelajuan sangat tinggi.', []),
    S('🧱','Kenapa banyak stage?','Stage yang kosong dibuang supaya rocket tidak perlu terus membawa berat yang tidak berguna.','Mengurangkan mass membantu stage seterusnya mencapai kelajuan lebih tinggi dengan propellant yang tinggal.', []),
    S('🌍','Orbit bukan sekadar naik tinggi','Untuk kekal mengorbit Earth, spacecraft perlu bergerak sangat laju ke sisi.','Ia sebenarnya sentiasa “jatuh” ke arah Earth, tetapi permukaan Earth melengkung menjauh pada kadar yang sepadan.', []),
    S('🛡️','Cabaran masuk semula','Apabila spacecraft masuk atmosphere pada kelajuan tinggi, udara dimampatkan dan memanaskan kenderaan.','Heat shield melindungi spacecraft dan penumpang atau cargo daripada suhu ekstrem.', [])
  ],

  elephant:[S('🐘','Badan besar yang sangat pintar','Elephant ialah mamalia darat terbesar dan hidup dalam kumpulan sosial yang kompleks.','Mereka berkomunikasi dengan bunyi, sentuhan dan getaran frekuensi rendah yang boleh bergerak jauh.', ['Trunk ialah gabungan hidung dan bibir atas.','Tusk ialah gigi incisor yang memanjang.']),S('👃','Trunk serba guna','Trunk digunakan untuk menghidu, minum, mengambil makanan, menyentuh dan menghasilkan bunyi.','Ia mempunyai puluhan ribu unit otot dan sangat kuat tetapi juga cukup halus untuk mengambil objek kecil.', []),S('👂','Telinga & suhu','Telinga yang besar membantu menyejukkan badan.','Banyak blood vessel dekat permukaan telinga melepaskan haba apabila elephant mengibaskan telinga.', []),S('🌿','Makan & habitat','Elephant ialah herbivore dan memerlukan banyak tumbuhan serta air.','Mereka membantu ekosistem dengan membuka laluan, menyebarkan biji benih dan mengubah landskap.', []),S('👨‍👩‍👧','Keluarga','Banyak kumpulan elephant diketuai oleh matriarch betina yang berpengalaman.','Pengetahuan lokasi air dan tindak balas terhadap bahaya boleh dipelajari secara sosial.', [])],
  lion:[S('🦁','Pemangsa sosial','Lion unik antara big cats kerana hidup dalam kumpulan yang dipanggil pride.','Kerjasama membantu memburu, mempertahankan kawasan dan menjaga anak.', []),S('🥩','Memburu','Lion menggunakan stealth, pecut pendek dan teamwork.','Mereka tidak sesuai mengejar mangsa untuk jarak sangat jauh kerana tubuhnya dibina untuk burst power.', []),S('🗣️','Roar','Roar digunakan untuk komunikasi dan menandakan territory.','Bunyi boleh didengar dari jarak beberapa kilometer dalam keadaan sesuai.', []),S('🌙','Aktif bila lebih sejuk','Lion banyak berehat pada siang dan lebih aktif waktu senja atau malam.','Ini membantu mengelakkan haba berlebihan dan memberi kelebihan ketika memburu.', []),S('🌍','Peranan ekosistem','Sebagai apex predator, lion membantu mengawal populasi herbivore dan struktur komuniti haiwan.','Kehilangan predator utama boleh memberi kesan berantai kepada ekosistem.', [])],
  giraffe:[S('🦒','Leher panjang, tulang leher tetap tujuh','Giraffe mempunyai tujuh cervical vertebrae seperti manusia, tetapi setiap satu sangat panjang.','Leher membantu mencapai daun tinggi dan juga digunakan dalam pertandingan antara jantan.', []),S('❤️','Jantung & tekanan darah','Darah perlu dipam jauh ke otak.','Giraffe mempunyai cardiovascular system yang disesuaikan untuk mengekalkan tekanan darah sesuai walaupun kepala bergerak naik turun.', []),S('👅','Makan daun','Lidah panjang dan bibir yang tangkas membantu mengambil daun, termasuk daripada pokok berduri.','Mereka ialah ruminant dan mencerna tumbuhan melalui sistem perut khusus.', []),S('🟤','Corak tompok','Setiap giraffe mempunyai pattern tompok yang unik.','Pattern juga berkait dengan jaringan blood vessel di bawah kulit yang mungkin membantu thermoregulation.', []),S('🏃','Berjalan & berlari','Kaki panjang membolehkan langkah besar dan kelajuan tinggi.','Giraffe menggunakan gait yang unik: kedua-dua kaki pada satu sisi boleh bergerak hampir bersama ketika berjalan.', [])],
  tiger:[S('🐯','Big cat bersendirian','Tiger biasanya hidup dan memburu sendirian dalam territory besar.','Mereka berkomunikasi melalui scent marks, scratch marks dan vocalization.', []),S('🟧','Strip unik','Pattern stripe setiap tiger berbeza, termasuk pada kulit di bawah bulu.','Camouflage membantu memecahkan outline badan dalam vegetation.', []),S('🏊','Pandai berenang','Tidak seperti banyak kucing domestik, tiger selesa berada dalam air.','Mereka boleh berenang merentas sungai dan menggunakan air untuk menyejukkan badan.', []),S('🥩','Ambush predator','Tiger mendekati mangsa secara senyap sebelum serangan jarak dekat.','Kaki belakang kuat membantu pecut dan lompatan.', []),S('🌳','Habitat berbeza','Tiger boleh hidup di rainforest, grassland, mangrove dan hutan sejuk.','Keperluan utama ialah mangsa mencukupi, air dan kawasan perlindungan.', [])],
  zebra:[S('🦓','Kenapa ada stripe?','Stripe zebra mungkin mempunyai beberapa fungsi, termasuk membantu mengurangkan gangguan biting flies.','Kajian juga menilai peranan dalam thermoregulation dan pengenalan sesama zebra, tetapi bukan semua fungsi telah diselesaikan sepenuhnya.', []),S('👥','Hidup berkumpulan','Zebra banyak hidup dalam herd yang memberi lebih banyak mata untuk mengesan predator.','Sesetengah species mempunyai unit keluarga yang stabil.', []),S('🌿','Grazer','Zebra makan rumput dan boleh memproses tumbuhan yang agak kasar.','Mereka membantu membentuk grassland dan boleh membuka laluan makanan untuk herbivore lain.', []),S('🏃','Pertahanan melalui gerakan','Kelajuan, stamina dan perubahan arah membantu mengelak predator.','Tendangan zebra juga boleh menjadi pertahanan yang kuat.', []),S('🧬','Bukan kuda berstripe','Zebra, horse dan donkey berada dalam genus Equus tetapi merupakan species berbeza.','Perbezaan tingkah laku dan evolusi menjadikan zebra tidak sekadar “kuda liar bercorak”.', [])],
  penguin:[S('🐧','Burung yang tidak terbang','Penguin ialah burung tetapi wing mereka berubah menjadi flipper untuk berenang.','Bentuk badan streamlined mengurangkan drag di dalam air.', []),S('🧥','Kekal panas','Feather yang padat, lapisan lemak dan tingkah laku seperti huddling membantu mengekalkan haba.','Tidak semua penguin hidup di kawasan ais; ada species dekat kawasan lebih sederhana.', []),S('🐟','Pemburu bawah air','Penguin memburu fish, krill atau squid bergantung pada species.','Mata dan badan mereka disesuaikan untuk pergerakan laju dalam air.', []),S('🥚','Pembiakan','Cara menjaga egg dan chick berbeza antara species.','Emperor penguin terkenal kerana jantan mengeram egg di atas kaki ketika musim sejuk Antartika.', []),S('🌊','Ocean sebagai rumah utama','Walaupun kita nampak penguin di darat, kebanyakan makanan mereka datang dari laut.','Kesihatan ocean sangat penting kepada survival populasi penguin.', [])],
  dolphin:[S('🐬','Mamalia, bukan ikan','Dolphin bernafas menggunakan paru-paru dan perlu naik ke permukaan.','Mereka melahirkan anak hidup dan menyusukan anak seperti mamalia lain.', []),S('📡','Echolocation','Banyak dolphin menghasilkan clicks dan mendengar echo untuk memahami sekeliling.','Otak memproses timing dan kekuatan echo untuk menganggarkan jarak, saiz dan bentuk objek.', []),S('👥','Sosial & komunikasi','Dolphin hidup dalam kumpulan dengan hubungan sosial kompleks.','Whistle tertentu boleh berfungsi seperti signature yang membantu mengenali individu.', []),S('🏊','Badan untuk berenang','Flipper membantu steering, tail flukes menghasilkan thrust, dan dorsal fin membantu stability.','Gerakan ekor utama adalah naik-turun, berbeza daripada kebanyakan fish yang menggerakkan ekor kiri-kanan.', []),S('🧠','Belajar & bermain','Dolphin boleh belajar tingkah laku daripada dolphin lain dan menunjukkan play behaviour.','Ini membantu saintis mengkaji cognition dan social learning.', [])],
  eagle:[S('🦅','Mata sangat tajam','Eagle mempunyai visual acuity yang tinggi untuk mengesan mangsa dari jauh.','Mata besar dan retina khusus membantu melihat detail ketika terbang tinggi.', []),S('🪶','Wing & soaring','Wing yang luas boleh menggunakan rising air untuk soar dengan penggunaan tenaga lebih rendah.','Tail membantu steering dan braking.', []),S('🦶','Talons','Kaki kuat dan talons tajam digunakan untuk menangkap dan memegang mangsa.','Beak lebih sesuai untuk mengoyak makanan berbanding menangkap.', []),S('🏔️','Nest besar','Sesetengah eagle membina nest yang digunakan dan ditambah bahan selama bertahun-tahun.','Lokasi tinggi memberi keselamatan dan akses kepada kawasan memburu.', []),S('🌿','Indicator ekosistem','Sebagai predator, eagle sensitif kepada perubahan pada food web dan pencemaran.','Populasi eagle boleh memberi petunjuk tentang kesihatan habitat.', [])],

  car:[S('🚗','Dari tenaga ke gerakan','Car perlu menukar energy source kepada rotation pada wheel.','Internal-combustion car menggunakan engine; electric car menggunakan motor. Gear, differential dan axle menghantar torque ke wheel.', []),S('🛞','Grip dengan jalan','Tire menghasilkan friction yang membolehkan acceleration, braking dan cornering.','Tanpa grip, wheel boleh berpusing tetapi kereta tidak bergerak seperti yang dikehendaki.', []),S('🛑','Bagaimana brake bekerja','Brake menukar kinetic energy kepada heat melalui friction atau regenerative braking.','ABS membantu mengelakkan wheel lock ketika hard braking supaya steering control lebih baik.', []),S('🧭','Steering & suspension','Steering mengubah arah wheel depan; suspension membantu tire kekal bersentuhan dengan jalan.','Shock absorber mengawal gerakan spring supaya kereta tidak terus melantun.', []),S('⚡','Petrol vs EV','EV mempunyai motor elektrik yang cekap dan boleh menghasilkan torque segera.','Petrol car menyimpan energy dalam fuel; EV menyimpan energy dalam battery. Kedua-duanya ada trade-off pada range, charging/refuelling dan manufacturing.', [])],
  airplane:[S('✈️','Empat force utama','Flight diterangkan dengan lift, weight, thrust dan drag.','Airplane kekal dalam penerbangan apabila forces dan motion mencapai keadaan sesuai; perubahan force membolehkan climb, descend atau accelerate.', []),S('🪽','Bagaimana wing menghasilkan lift','Wing membelokkan airflow dan menghasilkan pressure distribution yang memberi force ke atas.','Angle of attack, shape wing dan speed semuanya mempengaruhi lift.', []),S('🔥','Engine menghasilkan thrust','Jet engine menarik udara masuk, memampatkan, membakar fuel dan mempercepat gas ke belakang.','Propeller pula mempercepat sejumlah besar udara ke belakang untuk menghasilkan thrust.', []),S('🎛️','Cara pilot mengawal pesawat','Aileron mengawal roll, elevator mengawal pitch dan rudder mengawal yaw.','Flight-control surfaces mengubah aliran udara dan moment pada pesawat.', []),S('🛬','Takeoff & landing','Takeoff memerlukan speed yang cukup untuk menghasilkan lift; landing perlu mengurangkan energy secara terkawal.','Flap meningkatkan lift dan drag pada speed rendah, manakala brake dan reverse thrust membantu memperlahankan pesawat selepas touchdown.', [])],
  train:[S('🚆','Steel wheel atas steel rail','Contact area kecil dan rolling resistance rendah menjadikan train sangat cekap untuk membawa muatan besar.','Rail juga memandu arah, jadi steering berbeza daripada kereta.', []),S('⚡','Sumber kuasa','Train boleh menggunakan diesel-electric, electric overhead line atau third rail.','Banyak locomotive moden sebenarnya menggunakan electric motor pada axle walaupun energy asal datang daripada diesel generator.', []),S('🛤️','Switch & signal','Rail network menggunakan points/switches untuk mengubah laluan dan signals untuk memisahkan train dengan selamat.','Signalling moden boleh mengesan train dan menghadkan kelajuan secara automatik.', []),S('🛑','Kenapa train ambil masa lama untuk berhenti','Train sangat berat dan steel-on-steel mempunyai friction terhad.','Momentum besar bermaksud braking distance boleh menjadi sangat panjang, sebab itu signal perlu memberi amaran awal.', []),S('🚄','High-speed rail','Untuk bergerak sangat laju, track, aerodynamics, suspension dan signalling semuanya perlu direka khusus.','Curve lebih gentle dan grade separation membantu mengekalkan kelajuan tinggi dengan selamat.', [])],
  ship:[S('🚢','Kenapa kapal boleh terapung','Kapal menolak air ke tepi dan menerima buoyant force ke atas.','Walaupun dibuat daripada steel, bentuk hollow menjadikan purata density keseluruhan kapal lebih rendah daripada air yang dipindahkan.', []),S('⚓','Stability','Center of gravity dan center of buoyancy menentukan bagaimana kapal kembali tegak selepas condong.','Cargo perlu disusun dengan betul supaya stability kekal selamat.', []),S('⚙️','Propulsion','Engine memutar propeller atau sistem propulsion lain untuk menolak air ke belakang.','Rudder atau azimuth thruster mengubah arah thrust bagi steering.', []),S('🌊','Ombak & bentuk hull','Hull direka untuk memotong air, membawa muatan dan mengawal drag.','Bentuk berbeza digunakan untuk cargo ship, ferry, speedboat dan submarine kerana tugasnya tidak sama.', []),S('🧭','Navigation','Kapal moden menggabungkan GPS, radar, chart dan AIS.','Namun crew masih perlu memahami cuaca, depth, traffic dan collision rules.', [])],
  excavator:[S('🏗️','Hydraulic power','Excavator menggunakan pressurized hydraulic fluid untuk menggerakkan boom, arm dan bucket.','Cylinder menukar tekanan fluid kepada linear force yang sangat besar.', []),S('🦾','Boom, arm & bucket','Tiga bahagian ini bekerja seperti bahu, lengan dan tangan.','Mengawal beberapa cylinder serentak membolehkan bucket menggali, mengangkat dan membuang tanah dengan tepat.', []),S('🔄','Upper body boleh berpusing','Swing motor membolehkan house excavator berputar di atas undercarriage.','Ini mengurangkan keperluan menggerakkan seluruh machine setiap kali memindahkan material.', []),S('⛓️','Tracks','Track menyebarkan berat ke kawasan lebih luas dan memberi traction pada tanah lembut atau tidak rata.','Ia lebih stabil untuk kerja berat tetapi kurang efisien di jalan raya berbanding wheel.', []),S('🧰','Attachment','Bucket boleh diganti dengan breaker, grapple, auger dan attachment lain.','Satu base machine boleh melakukan banyak kerja berbeza dengan tool yang betul.', [])],
  bicycle:[S('🚲','Machine yang sangat cekap','Pedal memutar crank, chain memindahkan rotation ke rear wheel dan tire menolak jalan ke belakang.','Reaction daripada jalan menolak bicycle ke hadapan.', []),S('⚙️','Gear','Gear ratio menentukan berapa jauh wheel bergerak bagi setiap pusingan pedal.','Low gear memudahkan mendaki; high gear membantu bergerak laju di jalan rata.', []),S('⚖️','Balance & steering','Bicycle stabil melalui gabungan steering corrections, geometry dan motion.','Rider sentiasa membuat pembetulan kecil tanpa sedar.', []),S('🛑','Brake','Rim brake atau disc brake menghasilkan friction untuk mengurangkan wheel rotation.','Front brake biasanya boleh memberi braking force lebih besar tetapi perlu digunakan dengan kawalan.', []),S('💨','Aerodynamics','Pada speed tinggi, air resistance menjadi penggunaan energy yang besar.','Posisi badan lebih rendah dan pakaian lebih kemas boleh mengurangkan drag.', [])],

  volcano:[S('🌋','Magma vs lava','Magma ialah molten rock di bawah permukaan; apabila keluar ia dipanggil lava.','Gas terlarut, viscosity dan chemistry magma mempengaruhi jenis eruption.', []),S('🧱','Kenapa volcano terbentuk','Banyak volcano berlaku di plate boundary atau hotspot.','Di subduction zone, water daripada plate yang tenggelam membantu melting; di ridge, decompression membantu mantle melt.', []),S('💥','Eruption lembut atau explosive','Magma cair dan kurang gas boleh mengalir sebagai lava; magma lebih viscous boleh memerangkap gas dan menghasilkan eruption explosive.','Jenis rock dan kandungan silica memainkan peranan besar.', []),S('🏔️','Bentuk volcano','Shield volcano lebar dan landai; stratovolcano lebih curam; cinder cone lebih kecil.','Bentuk mencerminkan jenis eruption dan material yang terkumpul.', []),S('🌱','Bahaya & manfaat','Volcano boleh menghasilkan lava, ash, pyroclastic flow dan lahar, tetapi juga membentuk tanah subur dan geothermal resources.','Monitoring seismic activity, gas dan ground deformation membantu menilai risiko.', [])],
  earthquake:[S('🌎','Apa yang bergerak?','Earthquake berlaku apabila stress dalam rock dilepaskan secara tiba-tiba sepanjang fault.','Tenaga bergerak keluar sebagai seismic waves.', []),S('📍','Focus & epicenter','Focus atau hypocenter ialah titik dalam Bumi tempat rupture bermula; epicenter ialah titik di permukaan tepat di atasnya.','Damage tidak ditentukan oleh epicenter sahaja; depth, geology dan building design juga penting.', []),S('〰️','Seismic waves','P-waves paling cepat, S-waves lebih perlahan dan tidak bergerak melalui liquid, manakala surface waves sering menghasilkan shaking kuat di permukaan.','Sifat waves membantu saintis mengkaji interior Bumi.', []),S('📏','Magnitude vs intensity','Magnitude mengukur saiz event; intensity menerangkan kesan shaking di lokasi tertentu.','Dua tempat boleh mengalami intensity berbeza daripada earthquake yang sama.', []),S('🏠','Keselamatan','Semasa shaking: Drop, Cover and Hold On jika sesuai dengan panduan tempatan.','Building code, retrofitting dan preparedness mengurangkan risiko jauh lebih banyak daripada cuba “meramal” masa tepat earthquake.', [])],
  rain:[S('💧','Air tak hilang — ia berpindah','Rain ialah satu bahagian water cycle.','Air evaporate, menjadi water vapour, condense dalam cloud dan kembali ke permukaan sebagai precipitation.', []),S('☁️','Bagaimana droplet membesar','Water vapour condense pada tiny particles lalu membentuk droplet atau ice crystals.','Apabila cukup besar untuk mengatasi updraft dan air resistance, ia jatuh.', []),S('🌦️','Jenis hujan','Convectional rain datang daripada udara panas naik; frontal rain apabila air masses bertemu; orographic rain apabila udara dipaksa naik oleh gunung.','Malaysia banyak mengalami convection dan monsoon-related rainfall.', []),S('🌡️','Kenapa udara sejuk membantu hujan','Udara yang lebih sejuk biasanya boleh memegang kurang water vapour sebelum saturation.','Cooling boleh membawa udara ke dew point lalu condensation bermula.', []),S('🌊','Rainfall & flood','Hujan lebat tidak semestinya terus menjadi banjir; infiltration, drainage, river level, tide dan land use semua mempengaruhi runoff.','Urban surface yang impermeable boleh meningkatkan runoff.', [])],
  cloud:[S('☁️','Cloud bukan “wap” kosong','Cloud terdiri daripada tiny water droplets atau ice crystals yang terapung.','Water vapour sendiri invisible; kita nampak cloud kerana droplets/crystals scatter light.', []),S('🌡️','Bagaimana cloud terbentuk','Udara lembap naik, expand dan cool sehingga mencapai saturation.','Condensation berlaku pada aerosol atau condensation nuclei.', []),S('📚','Jenis cloud memberi petunjuk cuaca','Cumulus sering berbentuk gumpalan, stratus seperti layer, cirrus tinggi dan halus, cumulonimbus boleh menghasilkan thunderstorm.','Nama cloud sering menggabungkan bentuk dan altitude.', []),S('⚡','Thundercloud','Cumulonimbus mempunyai updraft kuat, ice particles dan charge separation.','Ini boleh menghasilkan lightning, heavy rain, hail dan strong wind.', []),S('🌍','Peranan dalam climate','Cloud boleh menyejukkan dengan memantulkan sunlight dan memanaskan dengan memerangkap infrared radiation.','Net effect bergantung pada jenis, altitude dan coverage.', [])],
  river:[S('🏞️','River ialah sistem aliran','Air bergerak dari kawasan lebih tinggi ke kawasan lebih rendah kerana gravity.','Catchment atau watershed ialah kawasan yang mengalirkan air ke river yang sama.', []),S('🪨','Erosion, transport, deposition','River menghakis rock, membawa sediment dan mendepositkannya apabila flow kehilangan energy.','Proses ini membentuk valley, meander, floodplain dan delta.', []),S('〰️','Kenapa river berliku','Sedikit perbezaan speed pada bank boleh menguatkan erosion di luar bend dan deposition di dalam bend.','Lama-kelamaan meander boleh menjadi semakin besar.', []),S('🌧️','River level berubah','Rainfall, soil moisture, dam operation, tide dan land cover mempengaruhi discharge.','Flood berlaku apabila water volume melebihi capacity channel atau drainage area.', []),S('🌱','Ekosistem & manusia','River membekalkan habitat, water, transport dan sediment, tetapi mudah terjejas oleh pollution dan development.','Riparian vegetation membantu stabilkan bank dan menyediakan habitat.', [])],
  mountain:[S('⛰️','Bagaimana mountain terbentuk','Banyak mountain terbentuk apabila tectonic plates bertembung, fold atau uplift crust.','Volcanic activity juga boleh membina mountain dari lava dan ash.', []),S('🪨','Mountain berubah','Erosion oleh water, ice, wind dan gravity sentiasa mengubah bentuk mountain.','Pembentukan boleh berlaku berjuta-juta tahun sementara landslide boleh mengubah slope dalam beberapa saat.', []),S('🌡️','Kenapa puncak lebih sejuk','Air pressure berkurang dengan altitude. Udara yang naik expand dan cool.','Suhu purata biasanya turun apabila altitude meningkat dalam troposphere.', []),S('💧','Water tower','Mountain menangkap precipitation dan menyimpan air sebagai snow, ice, soil moisture dan groundwater.','Banyak river besar bermula di highlands.', []),S('🌿','Zon kehidupan','Temperature dan moisture berubah dengan altitude, jadi vegetation dan animal community turut berubah.','Mendaki satu mountain boleh terasa seperti bergerak melalui beberapa climate zone.', [])],

  shark:[S('🦈','Ikan dengan rangka cartilage','Shark tidak mempunyai skeleton tulang seperti manusia; rangkanya terutama cartilage.','Ini lebih ringan dan fleksibel tetapi tetap cukup kuat untuk badan besar.', []),S('👃','Deria sangat kuat','Shark menggunakan smell, lateral line dan electroreception.','Ampullae of Lorenzini boleh mengesan medan elektrik kecil daripada muscle dan nerve activity mangsa.', []),S('🦷','Gigi sentiasa berganti','Banyak shark mempunyai beberapa barisan gigi dan gigi boleh diganti sepanjang hidup.','Bentuk gigi berbeza mengikut diet.', []),S('🌊','Buoyancy tanpa swim bladder','Shark banyak bergantung pada oil-rich liver dan dynamic lift daripada fins/badan.','Sesetengah species perlu terus berenang untuk ventilate gills dengan baik, tetapi tidak semua.', []),S('🌿','Peranan ekosistem','Banyak shark ialah predator penting yang membantu mengekalkan food web ocean.','Kadar reproduction yang perlahan menjadikan banyak species mudah terjejas jika overfished.', [])],
  octopus:[S('🐙','Lapan arm, tiga heart','Octopus ialah cephalopod dengan sistem badan sangat berbeza daripada vertebrate.','Dua heart mengepam darah ke gills dan satu ke seluruh badan.', []),S('🧠','Nervous system unik','Banyak neuron berada di arms, membolehkan kawalan dan sensing yang kompleks.','Arm boleh melakukan banyak processing tempatan sambil tetap diselaras oleh central brain.', []),S('🎨','Camouflage pantas','Chromatophore dan struktur kulit lain membolehkan perubahan warna dan texture dengan cepat.','Ini digunakan untuk camouflage, communication dan warning.', []),S('💨','Jet propulsion','Octopus boleh menarik water ke mantle lalu menolaknya keluar melalui siphon.','Jet memberi pecutan pantas walaupun crawling menggunakan arm lebih jimat energy.', []),S('🧩','Problem solving','Octopus boleh belajar, membuka container dan menggunakan objek sebagai shelter pada sesetengah species.','Cognition mereka berkembang secara berasingan daripada mammal, menjadikannya sangat menarik untuk sains.', [])],
  whale:[S('🐋','Mamalia laut','Whale bernafas dengan lungs dan perlu naik ke permukaan.','Blowhole ialah nostril yang berpindah ke bahagian atas kepala sepanjang evolusi.', []),S('🍼','Anak menyusu','Whale melahirkan anak hidup dan menghasilkan milk yang sangat kaya energy.','Calf perlu membesar cepat dalam persekitaran laut.', []),S('🍽️','Baleen vs toothed whales','Baleen whales menapis makanan kecil seperti krill; toothed whales mempunyai teeth dan sering memburu fish atau squid.','Dolphin sebenarnya sebahagian daripada toothed whale group.', []),S('🎵','Communication','Whale menggunakan sound kerana bunyi bergerak sangat baik dalam water.','Sesetengah calls boleh bergerak jauh; humpback whale terkenal dengan song yang kompleks.', []),S('🌍','Migration & carbon cycle','Banyak whale bermigrasi antara feeding dan breeding grounds.','Pergerakan nutrient dan whale falls juga memberi kesan kepada ocean ecosystem.', [])],
  coral:[S('🪸','Coral ialah haiwan','Coral colony terdiri daripada tiny polyps, bukan tumbuhan atau batu.','Banyak reef-building coral hidup bersama photosynthetic algae yang membekalkan banyak energy.', []),S('🏗️','Membina reef','Polyps membina calcium carbonate skeleton.','Apabila generasi demi generasi tumbuh, skeleton terkumpul menjadi reef structure yang besar.', []),S('🐠','Bandar bawah laut','Reef menyediakan food, shelter dan nursery untuk banyak species.','Walaupun menutup kawasan ocean yang kecil, biodiversity reef sangat tinggi.', []),S('🌡️','Coral bleaching','Heat stress boleh menyebabkan coral kehilangan symbiotic algae, lalu menjadi putih.','Bleached coral belum semestinya mati tetapi lebih lemah dan boleh mati jika stress berpanjangan.', []),S('🛡️','Kenapa reef penting kepada manusia','Reef membantu mengurangkan wave energy, menyokong fisheries dan tourism.','Pollution, warming, destructive fishing dan sedimentation boleh menjejaskan reef.', [])],
  'deep-sea':[S('🌑','Dunia tanpa cahaya Matahari','Di bawah photic zone, sunlight sangat sedikit atau tiada.','Organism bergantung pada sinking organic matter, hunting, scavenging atau chemosynthesis.', []),S('🧱','Tekanan sangat tinggi','Water pressure meningkat dengan depth.','Deep-sea animals mempunyai adaptation pada protein, membrane dan badan supaya berfungsi di bawah tekanan ekstrem.', []),S('✨','Bioluminescence','Banyak organism menghasilkan cahaya melalui chemical reaction.','Cahaya digunakan untuk menarik prey, berkomunikasi, camouflage atau mengelirukan predator.', []),S('🌋','Hydrothermal vents','Vent melepaskan fluid panas kaya mineral dari seafloor.','Bacteria chemosynthetic menggunakan chemical energy dan menyokong ecosystem tanpa bergantung secara langsung pada sunlight.', []),S('🔭','Masih belum banyak diteroka','Ocean dalam sukar dikaji kerana gelap, tekanan tinggi dan sangat luas.','ROV, autonomous vehicle dan submersible membantu saintis melihat habitat yang jarang disentuh manusia.', [])],

  trex:[S('🦖','Predator besar Late Cretaceous','Tyrannosaurus rex hidup kira-kira 68–66 juta tahun lalu di western North America.','Ia mempunyai skull besar, powerful jaws, kaki belakang kuat dan arm yang sangat kecil tetapi berotot.', []),S('🦷','Bite force','Gigi T. rex tebal dan sesuai menghancurkan flesh serta bone.','Coprolite dan bite marks memberi petunjuk bahawa ia mampu memproses bone.', []),S('🏃','Bagaimana ia bergerak','Saintis menggunakan bone, muscle reconstruction dan computer models untuk menganggar posture dan speed.','Ia bukan semestinya sprinter ekstrem seperti dalam filem; kestabilan dan body mass sangat penting.', []),S('👃','Deria','Skull anatomy menunjukkan sense of smell yang kuat dan binocular vision yang baik.','Ini menyokong peranan sebagai active predator, walaupun scavenging juga mungkin dilakukan bila peluang ada.', []),S('🧪','Bagaimana kita tahu?','Fossil bone, track, tooth marks dan biomechanical analysis semuanya digabungkan.','Sains dinosaur sentiasa berubah apabila specimen baru ditemui.', [])],
  triceratops:[S('🦕','Tiga horn & frill','Triceratops ialah herbivore besar dengan dua horn di atas mata, satu di hidung dan frill tulang di belakang kepala.','Struktur ini mungkin digunakan untuk defence, display dan species recognition.', []),S('🌿','Makan tumbuhan','Beak dan battery of teeth membantu memotong dan menghancurkan vegetation.','Gigi sentiasa diganti apabila haus.', []),S('🦴','Badan berat','Empat kaki menyokong skull dan badan yang sangat berat.','Cara postur kaki direkonstruksi daripada joint surfaces, track dan biomechanical modelling.', []),S('⚔️','T. rex vs Triceratops','Bite marks yang sembuh pada fossil menunjukkan interaksi sebenar dengan tyrannosaur.','Tetapi kita tidak boleh tahu bahawa setiap pertemuan menjadi “pertarungan” dramatik seperti filem.', []),S('🧪','Fossil membantu ubah idea','Banyak skull dan specimen membolehkan saintis mengkaji growth, variation dan injury.','Frill dan horn berubah bentuk apabila individu membesar.', [])],
  brachiosaurus:[S('🦕','Sauropod tinggi','Brachiosaurus mempunyai forelimb lebih panjang daripada hindlimb, memberi bahu yang tinggi.','Leher panjang membantu mencapai vegetation pada ketinggian berbeza.', []),S('🌿','Makan banyak tumbuhan','Badan gergasi memerlukan pengambilan tumbuhan besar.','Ia mungkin menelan vegetation tanpa chewing halus seperti mammal dan mencerna melalui gut yang besar.', []),S('🫀','Cabaran badan tinggi','Mengalirkan darah ke kepala pada leher panjang memerlukan cardiovascular adaptation.','Saintis masih membincangkan posture leher dan physiology tepat berdasarkan fossil dan comparison dengan haiwan hidup.', []),S('🦴','Tulang ringan','Banyak sauropod mempunyai vertebrae dengan air spaces, mengurangkan mass tanpa kehilangan terlalu banyak strength.','Sistem air sac serupa konsep dengan burung mungkin membantu respiration.', []),S('🌍','Jurassic ecosystem','Brachiosaurus hidup bersama banyak dinosaur lain dalam environment yang kompleks.','Fossil flora dan sediment membantu reconstruct habitat, bukan bone sahaja.', [])],
  raptor:[S('🦖','“Raptor” sebenar lebih kecil','Velociraptor sebenar jauh lebih kecil daripada gambaran popular dalam banyak filem.','Ia dromaeosaur dengan sickle-shaped claw pada kaki dan feather evidence daripada kumpulan rapat.', []),S('🪶','Hubungan dengan burung','Banyak theropod mempunyai feather atau struktur seperti feather.','Birds moden ialah keturunan theropod dinosaur, jadi feather bukan sesuatu yang pelik dalam kumpulan ini.', []),S('🦶','Sickle claw','Large claw mungkin membantu mencengkam prey, bukan semestinya “menikam” seperti pisau.','Biomechanics mencadangkan fungsi grasping dan pinning pada sesetengah dromaeosaur.', []),S('🧠','Agile hunter','Badan ringan, tail stiff dan kaki belakang kuat membantu balance dan maneuvering.','Tahap intelligence sering dibesar-besarkan dalam fiction, tetapi brain relatifnya memang menarik.', []),S('🏜️','Famous fighting fossil','Satu fossil Velociraptor dan Protoceratops ditemui dalam posisi bertarung.','Ia memberi snapshot tingkah laku yang sangat jarang tetapi masih perlu ditafsir dengan berhati-hati.', [])],
  fossil:[S('🪨','Fossil ialah rekod kehidupan lama','Fossil boleh berupa bone, shell, leaf impression, footprint, burrow atau bahkan feces yang membatu.','Ia bukan semua “tulang yang jadi batu”; ada banyak proses preservation.', []),S('⏳','Bagaimana fossil terbentuk','Organism biasanya perlu tertimbus dengan cepat supaya decay dan scavenging berkurang.','Mineral boleh mengisi ruang, mengganti tissue atau meninggalkan mould/cast.', []),S('📚','Rock layer ialah timeline','Dalam undisturbed sedimentary layers, lapisan bawah biasanya lebih lama daripada lapisan atas.','Radiometric dating dan index fossils membantu meletakkan umur lebih tepat.', []),S('🕵️','Fossil bukan cerita lengkap','Fossil record biased kerana soft tissue jarang kekal dan tidak semua habitat mudah memfosil.','Saintis perlu bezakan antara evidence yang ada dan perkara yang masih hypothesis.', []),S('🔬','Teknologi moden','CT scan, isotope analysis dan microscopy membolehkan kita belajar tanpa merosakkan specimen.','Kadang-kadang protein, pigment structure atau tiny internal anatomy boleh dikaji.', [])],

  seed:[S('🌰','Seed ialah “starter pack” tumbuhan','Seed biasanya mengandungi embryo, food reserve dan protective coat.','Ia membolehkan tumbuhan menunggu keadaan sesuai sebelum mula membesar.', []),S('💧','Germination','Water mengaktifkan metabolism, seed membengkak dan embryo mula tumbuh.','Oxygen dan temperature sesuai juga penting; sesetengah seed memerlukan light atau cue tertentu.', []),S('⬇️','Root dulu','Radicle biasanya keluar dahulu untuk anchoring dan menyerap water.','Shoot kemudian tumbuh ke arah light.', []),S('🎒','Food reserve','Cotyledon atau endosperm membekalkan energy sebelum seedling boleh photosynthesize secukupnya.','Apabila leaves berkembang, tumbuhan semakin bergantung pada sunlight.', []),S('🌬️','Seed dispersal','Seed boleh disebar oleh wind, water, animal atau explosive fruit.','Dispersal mengurangkan competition dengan parent plant dan membantu colonize tempat baru.', [])],
  roots:[S('🌱','Anchor & absorber','Root memegang tumbuhan dan menyerap water serta mineral.','Root hair menambah surface area supaya absorption lebih berkesan.', []),S('⬇️','Tumbuh mengikut gravity','Root menunjukkan gravitropism positif — cenderung tumbuh ke bawah.','Hormone dan sensing dalam root tip membantu arah pertumbuhan.', []),S('🚰','Water masuk dan naik','Water masuk ke root melalui osmosis dan bergerak ke xylem.','Transpiration daripada leaves membantu menarik column water ke atas.', []),S('🍠','Simpan makanan','Sesetengah root membesar untuk menyimpan carbohydrate, contohnya carrot dan sweet potato.','Ini membantu tumbuhan bertahan atau tumbuh semula.', []),S('🤝','Kerjasama dengan microbe','Mycorrhizal fungi boleh membantu root mendapatkan water dan mineral; bacteria tertentu membantu nitrogen cycle.','Root ecosystem ialah komuniti hidup, bukan sekadar paip air.', [])],
  leaf:[S('🍃','Solar panel tumbuhan','Leaf direka untuk menangkap light dan melakukan photosynthesis.','Permukaan luas membantu penyerapan light, manakala vein membawa water dan sugar.', []),S('🔬','Stomata','Tiny pores dipanggil stomata mengawal pertukaran carbon dioxide, oxygen dan water vapour.','Guard cells membuka atau menutup stomata mengikut keadaan.', []),S('☀️','Chlorophyll','Chlorophyll menyerap terutama red dan blue light dan memantulkan lebih banyak green, sebab itu daun nampak hijau.','Pigment lain turut membantu dan boleh kelihatan apabila chlorophyll berkurang.', []),S('💧','Transpiration','Water vapour keluar melalui stomata.','Ini membantu cooling dan menarik lebih banyak water dari root ke atas.', []),S('🧬','Bentuk ikut habitat','Leaf desert, rainforest dan aquatic plant boleh sangat berbeza.','Thickness, wax, hair dan shape ialah adaptation terhadap water, light dan temperature.', [])],
  flower:[S('🌸','Organ reproduction','Flower mengandungi struktur yang menghasilkan pollen dan ovule.','Pollination membawa pollen ke bahagian female; fertilization menghasilkan embryo dalam seed.', []),S('🐝','Pollinator','Colour, scent, nectar dan shape boleh menarik bee, butterfly, bird, bat atau pollinator lain.','Sesetengah flower pula bergantung pada wind.', []),S('🌱','Dari flower ke fruit','Selepas fertilization, ovary pada banyak flowering plants berkembang menjadi fruit dan ovule menjadi seed.','Fruit membantu melindungi dan menyebarkan seed.', []),S('🕒','Timing','Flowering boleh dikawal oleh day length, temperature dan umur tumbuhan.','Ini membantu tumbuhan menyelaras reproduction dengan season dan pollinator.', []),S('🎨','Kenapa banyak warna?','Pigment dan UV patterns boleh menjadi signal kepada pollinator.','Apa yang dilihat serangga tidak semestinya sama dengan apa yang dilihat manusia.', [])],
  tree:[S('🌳','Struktur tinggi hidup','Tree mempunyai root, trunk, branch dan leaves yang bekerjasama mengangkut water, sugar dan memberi support.','Wood mengandungi banyak xylem yang telah matang dan lignin yang memberi strength.', []),S('💧','Mengangkat water tinggi','Transpiration pull, cohesion dan xylem membantu water naik dari root ke canopy.','Tree tidak mempunyai “pump” seperti heart.', []),S('⭕','Growth ring','Di climate bermusim, cambium menghasilkan wood dengan pattern yang boleh membentuk annual rings.','Ring width boleh memberi petunjuk tentang growth conditions tetapi interpretasi perlu berhati-hati.', []),S('🌬️','Carbon cycle','Tree menyimpan carbon dalam wood, root dan soil melalui photosynthesis.','Namun forest carbon bergantung pada growth, decay, fire dan land management.', []),S('🏘️','Habitat','Satu tree boleh menyokong insect, bird, fungus, epiphyte dan microbe yang banyak.','Old trees dan dead wood juga sangat penting kepada biodiversity.', [])],
  photosynthesis:[S('☀️','Menukar light kepada chemical energy','Plants menggunakan light energy untuk membina sugar daripada carbon dioxide dan water.','Oxygen dilepaskan sebagai by-product penting kepada atmosphere.', []),S('🍃','Berlaku dalam chloroplast','Chlorophyll dalam chloroplast menangkap light.','Light reactions menghasilkan energy carriers; Calvin cycle menggunakan carbon dioxide untuk membina carbohydrate.', []),S('🌬️','Carbon dioxide masuk','CO₂ masuk melalui stomata pada leaves.','Tumbuhan perlu seimbangkan pengambilan CO₂ dengan kehilangan water.', []),S('💧','Water datang dari root','Water diserap root dan bergerak melalui xylem.','Oxygen yang dilepaskan semasa photosynthesis berasal daripada splitting water molecules dalam light reactions.', []),S('🌍','Asas food web','Hampir semua food chain bergantung secara langsung atau tidak langsung pada photosynthetic organisms.','Ia juga memainkan peranan utama dalam global carbon dan oxygen cycles.', [])],

  heart:[S('❤️','Pump dua bahagian','Right side menghantar blood ke lungs; left side menghantar oxygen-rich blood ke seluruh badan.','Empat chamber — dua atria dan dua ventricles — memisahkan aliran dan membina pressure yang sesuai.', []),S('🚪','Valve','Valve membuka satu arah dan membantu menghalang backflow.','Bunyi “lub-dub” datang terutama daripada penutupan valve.', []),S('⚡','Electrical system','Heart mempunyai pacemaker semula jadi dan conduction pathway yang menyelaras contraction.','Electrical signal bergerak melalui atria kemudian ventricles.', []),S('🩸','Coronary circulation','Heart muscle sendiri memerlukan oxygen melalui coronary arteries.','Blockage boleh mengurangkan blood flow ke muscle dan menjadi kecemasan perubatan.', []),S('🏃','Heart berubah ikut aktiviti','Exercise meningkatkan keperluan oxygen, jadi heart rate dan stroke volume boleh meningkat.','Latihan jangka panjang boleh meningkatkan efficiency cardiovascular system.', [])],
  lungs:[S('🫁','Tempat pertukaran gas','Lungs membawa oxygen dari air ke blood dan membuang carbon dioxide.','Pertukaran berlaku terutamanya di jutaan tiny air sacs yang dipanggil alveoli.', []),S('🫧','Alveoli','Dinding alveoli sangat nipis dan dikelilingi capillary.','Surface area yang besar mempercepat diffusion gas.', []),S('↕️','Cara bernafas','Diaphragm mengecut dan turun semasa inhalation, membesarkan chest cavity dan menurunkan pressure.','Air masuk kerana pressure difference; exhalation berlaku apabila volume berkurang.', []),S('🧹','Airway protection','Mucus menangkap particle dan cilia membantu menggerakkannya keluar.','Coughing dan sneezing ialah tambahan defence mechanisms.', []),S('🏃','Exercise','Semasa exercise, breathing rate dan depth meningkat untuk memenuhi demand oxygen dan membuang lebih CO₂.','Lungs bekerja rapat dengan heart, blood dan muscles.', [])],
  brain:[S('🧠','Network besar','Brain mengandungi berbilion neuron dan lebih banyak support cells yang membentuk network kompleks.','Neuron berkomunikasi menggunakan electrical signals dan chemical neurotransmitters.', []),S('🗺️','Bahagian utama','Cerebrum terlibat dalam thought, senses dan voluntary movement; cerebellum penting untuk coordination; brainstem mengawal banyak fungsi asas.','Bahagian brain saling bekerjasama, bukan bekerja secara terasing sepenuhnya.', []),S('🧠','Belajar mengubah connection','Learning boleh menguatkan atau mengubah synaptic connections.','Ini dipanggil neuroplasticity dan berlaku sepanjang hidup, walaupun kadar dan bentuknya berubah dengan umur.', []),S('😴','Sleep penting','Sleep membantu memory consolidation, regulation dan recovery.','Kurang tidur boleh mengganggu attention, mood dan learning.', []),S('🛡️','Perlindungan','Skull, meninges dan cerebrospinal fluid membantu melindungi brain.','Blood-brain barrier juga mengawal banyak bahan yang boleh masuk dari blood.', [])],
  bones:[S('🦴','Skeleton hidup','Bone bukan struktur mati; ia sentiasa diubah suai oleh cells.','Bone menyokong badan, melindungi organ, menyimpan mineral dan menyediakan lever untuk movement.', []),S('🏭','Bone marrow','Marrow dalam sesetengah bone menghasilkan blood cells.','Red marrow sangat aktif dalam menghasilkan red cells, white cells dan platelets.', []),S('💪','Bone + muscle','Muscle menarik tendon, tendon menarik bone dan joint menjadi pivot.','Movement ialah kerjasama sistem musculoskeletal, bukan kerja muscle sahaja.', []),S('🔄','Remodelling','Osteoclast memecahkan bone lama dan osteoblast membina bone baru.','Load daripada activity boleh memberi signal untuk menguatkan structure.', []),S('🥛','Nutrient & growth','Calcium, phosphorus, protein dan vitamin D penting untuk bone health.','Growth plate pada kanak-kanak membolehkan long bones memanjang.', [])],
  stomach:[S('🍽️','Storage & mixer','Stomach menyimpan makanan sementara dan menggaulkannya dengan gastric juice.','Muscle contraction menghasilkan chyme sebelum makanan bergerak ke small intestine.', []),S('🧪','Acid & enzyme','Hydrochloric acid membantu membunuh banyak microbe dan menyediakan pH untuk enzyme seperti pepsin.','Mucus layer melindungi lining stomach daripada acid dan enzyme.', []),S('🚪','Sphincter','Valve-like muscle membantu mengawal masuk dan keluar makanan.','Lower esophageal sphincter mengurangkan reflux, manakala pyloric sphincter mengawal chyme ke duodenum.', []),S('🧬','Bukan tempat semua nutrient diserap','Kebanyakan nutrient absorption berlaku di small intestine.','Stomach menyerap hanya jumlah terhad bahan tertentu.', []),S('🧠','Gut-brain connection','Nervous system dan hormone menyelaras hunger, fullness dan digestion.','Emosi dan stress juga boleh mempengaruhi sensation pada digestive system.', [])],
  senses:[S('👁️','Senses lebih daripada lima','Kita biasa belajar sight, hearing, smell, taste dan touch, tetapi badan juga mengesan balance, temperature, pain dan posisi joint.','Brain menggabungkan banyak input untuk membina gambaran tentang dunia.', []),S('👀','Vision','Light difokuskan ke retina, photoreceptor menukar light kepada signal dan brain memproses pattern.','Kita sebenarnya “melihat” melalui kerjasama eye dan brain.', []),S('👂','Hearing & balance','Sound vibration bergerak melalui eardrum dan middle-ear bones ke cochlea.','Inner ear juga mempunyai vestibular organs yang mengesan rotation dan acceleration.', []),S('👃','Smell & taste','Taste receptor mengesan kategori chemical tertentu; smell menyumbang besar kepada flavor.','Sebab itu makanan terasa kurang berperisa ketika hidung tersumbat.', []),S('✋','Touch & body sense','Skin receptor mengesan pressure, vibration, temperature dan pain.','Proprioception memberitahu brain kedudukan anggota badan tanpa perlu melihat.', [])],

  'traffic-light':[S('🚦','Simple rule, complex system','Traffic light mengawal conflict antara aliran traffic dan pedestrian.','Controller memilih phase berdasarkan timing plan atau sensor input.', []),S('🔴🟡🟢','Kenapa tiga warna?','Red digunakan untuk stop, amber untuk transition/warning dan green untuk movement yang dibenarkan.','Standardisasi penting supaya pengguna jalan memahami signal dengan cepat.', []),S('👁️','Sensor','Intersection boleh menggunakan inductive loop, radar, camera atau button pedestrian.','Data ini membantu controller menyesuaikan green time.', []),S('🧠','Coordination','Beberapa traffic light boleh diselaraskan untuk menghasilkan “green wave”.','Timing perlu mempertimbangkan volume, pedestrian, turning movement dan safety.', []),S('⚠️','Fail-safe','Controller direka supaya conflict green tidak berlaku serentak.','Jika fault serius, sistem boleh masuk flashing mode atau all-red bergantung pada design.', [])],
  fan:[S('🌀','Fan tidak “mencipta sejuk”','Fan menggerakkan udara. Ia membantu badan menyejuk kerana evaporation dan meningkatkan heat transfer dari kulit.','Suhu bilik sendiri mungkin tidak turun banyak hanya kerana fan.', []),S('⚡','Motor','Electric motor menukar electrical energy kepada rotation.','Magnetic field dalam motor menghasilkan torque pada rotor.', []),S('🪽','Blade','Blade mempunyai angle yang mempercepat udara ke arah tertentu.','Shape, pitch dan speed mempengaruhi airflow, noise dan efficiency.', []),S('🎛️','Speed control','Fan moden boleh mengubah voltage, phase control atau menggunakan electronic motor control.','Brushless DC motor boleh sangat efficient dan mudah dikawal.', []),S('🧹','Safety & maintenance','Dust pada blade mengurangkan kebersihan airflow dan boleh menyebabkan imbalance.','Guard membantu mengelakkan sentuhan dengan blade yang bergerak.', [])],
  elevator:[S('🛗','Cab bergerak pada guide rails','Elevator moden biasanya traction atau hydraulic.','Traction elevator menggunakan motor, rope/belt dan counterweight; hydraulic menggunakan piston untuk mengangkat car.', []),S('⚖️','Counterweight','Counterweight mengimbangi sebahagian mass car dan average load.','Motor tidak perlu mengangkat keseluruhan berat setiap kali, meningkatkan efficiency.', []),S('🧠','Control system','Controller memilih car, floor dan route untuk meminimumkan waiting dan travel time.','Bangunan besar boleh menggunakan group control algorithms.', []),S('🛑','Safety','Elevator mempunyai brake, door interlock, overspeed governor dan safety gear.','Car tidak sepatutnya bergerak normal jika door belum locked.', []),S('🚪','Kenapa ada dua pintu','Car door bergerak bersama landing door hanya apabila elevator berada di floor yang betul.','Landing door kekal locked apabila car tiada, melindungi shaft.', [])],
  electricity:[S('⚡','Electric charge & current','Current ialah pergerakan charge melalui circuit.','Voltage ialah perbezaan electric potential yang boleh “mendorong” charge, manakala resistance melawan current.', []),S('🔁','Circuit mesti lengkap','Untuk current berterusan dalam simple circuit, laluan perlu membentuk loop tertutup.','Switch membuka atau menutup laluan.', []),S('🔋','DC vs AC','Battery membekalkan DC dengan arah current satu arah secara konvensional; grid rumah biasanya AC yang berubah arah berkala.','Transformer sangat berguna dengan AC untuk menukar voltage.', []),S('🏭','Dari power plant ke rumah','Electricity dihantar pada high voltage untuk mengurangkan loss, kemudian diturunkan melalui transformer.','Grid mengimbangi generation dan demand hampir setiap saat.', []),S('🛡️','Safety','Fuse, circuit breaker, earthing dan RCD membantu mengurangkan risiko shock dan fire.','Electricity household boleh berbahaya — eksperimen mesti menggunakan low-voltage safe kits dan pengawasan yang sesuai.', [])],

  continents:[S('🌍','Benua ialah pembahagian besar daratan','Model tujuh benua biasa ialah Asia, Africa, North America, South America, Antarctica, Europe dan Australia/Oceania.','Cara mengira benua boleh berbeza mengikut budaya dan sistem pendidikan.', []),S('🧩','Benua bergerak','Tectonic plates bergerak beberapa centimeter setahun.','Supercontinent lama seperti Pangaea berpecah dan daratan terus berubah.', []),S('🌦️','Climate berbeza','Latitude, altitude, ocean current dan landform menghasilkan climate yang sangat pelbagai dalam satu benua.','Asia contohnya merangkumi Arctic hingga tropical rainforest.', []),S('🧑‍🤝‍🧑','Bukan sama dengan negara','Benua mengandungi banyak negara dan masyarakat dengan bahasa serta budaya berbeza.','Sempadan politik boleh berubah jauh lebih cepat daripada geologi benua.', []),S('🌊','Ocean menghubungkan','Ocean bukan hanya memisahkan benua — ia juga menghubungkan trade, climate dan migration.','Current ocean memindahkan haba antara kawasan dunia.', [])],
  malaysia:[S('🇲🇾','Dua wilayah utama','Malaysia terdiri daripada Semenanjung Malaysia serta Sabah dan Sarawak di Borneo, dipisahkan oleh Laut China Selatan.','Geografi ini menghasilkan coastline, mountain, river dan rainforest yang pelbagai.', []),S('🌧️','Tropical climate','Malaysia panas dan lembap dengan rainfall tinggi serta monsoon pattern.','Northeast dan Southwest Monsoon mempengaruhi lokasi dan musim hujan secara berbeza.', []),S('🌳','Biodiversity','Rainforest Malaysia menyokong banyak species tumbuhan dan haiwan.','Habitat termasuk lowland forest, montane forest, mangrove, river dan coral reef.', []),S('🏙️','Manusia & ekonomi','Bandar, agriculture, manufacturing, services dan ports saling berkait dengan geography.','Strait of Malacca ialah salah satu laluan shipping penting dunia.', []),S('🗣️','Bahasa & budaya','Bahasa Melayu ialah bahasa kebangsaan, tetapi banyak bahasa dan tradisi lain hidup bersama.','Memahami Malaysia bermaksud belajar geografi, sejarah dan masyarakat secara serentak.', [])],
  japan:[S('🗾','Negara kepulauan','Japan terdiri daripada ribuan island dengan empat main islands yang besar.','Kedudukannya di Pacific Ring of Fire menjadikannya aktif secara tectonic.', []),S('🌋','Earthquake & volcano','Plate interactions menghasilkan earthquake dan volcanic activity.','Japan membina building code, monitoring dan disaster preparedness yang maju untuk mengurus risiko.', []),S('🌦️','Climate panjang dari utara ke selatan','Hokkaido sejuk dan bersalji, manakala Okinawa subtropical.','Ocean current dan mountain juga mengubah local climate.', []),S('🚄','Transport','High-density city dan rail network membantu ramai orang bergerak dengan cekap.','Shinkansen terkenal dengan dedicated high-speed rail infrastructure.', []),S('🎎','Tradisi + teknologi','Japan menggabungkan heritage lama dengan industrial dan digital technology moden.','Culture tidak boleh diringkaskan kepada satu stereotype — setiap region mempunyai identity tersendiri.', [])],
  egypt:[S('🇪🇬','Civilization di sepanjang Nile','Nile menyediakan water dan fertile soil dalam kawasan yang kebanyakannya desert.','Flood cycle sejarah membantu agriculture dan pertumbuhan settlement.', []),S('🔺','Pyramid','Pyramid ialah monument funerary yang dibina menggunakan organisasi tenaga kerja, engineering dan stone transport yang kompleks.','Great Pyramid of Giza dibina ribuan tahun lalu dan kekal sebagai pencapaian engineering luar biasa.', []),S('🏜️','Desert environment','Sebahagian besar Egypt ialah arid.','Settlement moden masih tertumpu dekat Nile valley, delta dan coastal areas kerana access water dan infrastructure.', []),S('📜','Writing & records','Hieroglyph ialah salah satu sistem tulisan Mesir purba.','Papyrus, inscriptions dan archaeology membantu reconstruct sejarah, tetapi tidak semua perkara diketahui dengan pasti.', []),S('🌍','Egypt moden','Egypt hari ini ialah negara moden dengan bandar besar, industry, tourism dan kedudukan strategik melalui Suez Canal.','Belajar Egypt perlu bezakan ancient history daripada masyarakat hari ini.', [])],
  flags:[S('🏳️','Flag ialah simbol','Flag menggunakan colour, shape dan emblem untuk mewakili negara, wilayah atau organisasi.','Meaning rasmi datang daripada sejarah dan undang-undang setiap tempat — jangan anggap semua warna mempunyai maksud universal.', []),S('📐','Design','Banyak flag menggunakan geometry mudah supaya mudah dikenali dari jauh.','Aspect ratio, exact colour dan emblem boleh mempunyai specification rasmi.', []),S('🔁','Ada pattern serupa','Cross, stripes, stars dan crescents muncul dalam banyak flag tetapi sejarahnya berbeza.','Similar design tidak semestinya bermaksud negara mempunyai hubungan langsung.', []),S('📚','Flag berubah','Apabila political system atau negara berubah, flag juga boleh berubah.','Mengkaji flag boleh menjadi pintu masuk kepada sejarah dan geography.', []),S('🤝','Respect & protocol','Sesetengah negara mempunyai rules tentang cara flag dipamer atau digunakan.','Belajar flag juga bermaksud menghormati simbol masyarakat lain.', [])],

  gravity:[S('🍎','Gravity ialah attraction antara mass','Semua objek bermass menarik antara satu sama lain.','Kita paling terasa gravity Earth kerana mass Earth sangat besar dan kita dekat dengannya.', []),S('📏','Lebih mass, lebih kuat; lebih jauh, lebih lemah','Gravitational force meningkat dengan mass dan menurun dengan jarak.','Ini menjelaskan kenapa Moon mengorbit Earth dan Earth mengorbit Sun.', []),S('🛰️','Orbit ialah free fall','Satellite dalam orbit sebenarnya sentiasa jatuh ke arah Earth.','Ia bergerak ke sisi cukup laju sehingga “terlepas” permukaan yang melengkung.', []),S('⚖️','Mass vs weight','Mass ialah amount of matter/inertia; weight ialah force gravity pada mass.','Mass sama di Moon, tetapi weight lebih kecil kerana gravitational field Moon lebih lemah.', []),S('🌌','Gravity membentuk universe','Gravity membantu membentuk star, planet, galaxy dan large-scale structure.','Walaupun paling lemah antara fundamental forces pada particle scale, ia dominan pada astronomical scale kerana sentiasa attractive.', [])],
  magnet:[S('🧲','Magnetic field','Magnet mempunyai field yang memberi force pada magnet lain dan moving charges.','Field lines ialah cara visual menggambarkan direction dan strength, bukan “benang” sebenar.', []),S('N/S','Pole','Like poles repel dan opposite poles attract.','Memotong bar magnet menghasilkan magnet lebih kecil dengan north dan south pole, bukan satu pole tunggal biasa.', []),S('⚛️','Dari electron','Magnetism datang daripada motion dan quantum properties electron.','Dalam ferromagnetic material, banyak tiny magnetic domains boleh align.', []),S('⚡','Electricity & magnetism','Current menghasilkan magnetic field; changing magnetic field pula boleh induce voltage.','Inilah asas motor, generator dan transformer.', []),S('🌍','Earth sebagai magnet','Flow metal cair dalam outer core membantu menghasilkan geomagnetic field.','Compass align dengan field ini, walaupun magnetic north tidak sama tepat dengan geographic north.', [])],
  light:[S('💡','Light membawa energy','Visible light ialah sebahagian kecil electromagnetic spectrum.','Radio, infrared, ultraviolet, X-ray dan gamma ray ialah keluarga electromagnetic radiation dengan wavelength berbeza.', []),S('🌈','Colour','White light boleh dipecahkan kepada spectrum warna.','Object nampak warna tertentu kerana kombinasi wavelength yang dipantulkan ke mata.', []),S('🪞','Reflection','Apabila light memantul dari permukaan licin, angle incidence sama dengan angle reflection.','Mirror menghasilkan image kerana reflection yang teratur.', []),S('🥤','Refraction','Light menukar speed dan arah apabila bergerak antara material dengan optical properties berbeza.','Ini sebab straw dalam water nampak bengkok dan lens boleh memfokus light.', []),S('🌌','Kelajuan sangat tinggi','Light dalam vacuum bergerak kira-kira 300,000 km/s.','Walaupun sangat laju, jarak angkasa sangat besar sehingga kita melihat objek jauh seperti keadaan masa lalu.', [])],
  sound:[S('🔊','Sound ialah vibration','Sound memerlukan medium seperti air, water atau solid untuk merambat sebagai pressure wave.','Dalam vacuum, sound biasa tidak boleh bergerak kerana tiada particle untuk memindahkan vibration.', []),S('↕️','Frequency & pitch','Frequency lebih tinggi biasanya dirasai sebagai pitch lebih tinggi.','Human hearing mempunyai julat terhad; animal lain boleh mendengar frequency yang kita tidak boleh.', []),S('📢','Amplitude & loudness','Amplitude berkait dengan perubahan pressure yang lebih besar dan biasanya bunyi lebih kuat.','Perceived loudness juga bergantung pada frequency dan human ear.', []),S('🏃','Speed sound','Sound bergerak pada speed berbeza dalam material berbeza dan dipengaruhi temperature.','Dalam air pada suhu bilik ia sekitar 343 m/s, jauh lebih perlahan daripada light.', []),S('👂','Hearing','Eardrum vibrate, middle-ear bones memindahkan vibration, cochlea menukarnya kepada neural signal.','Brain menentukan pitch, location dan meaning berdasarkan pattern signal.', [])],
  states:[S('🧊','Solid','Particle dalam solid biasanya rapat dan bergetar sekitar posisi.','Solid mengekalkan shape dan volume dalam keadaan biasa.', []),S('💧','Liquid','Particle masih dekat tetapi boleh bergerak antara satu sama lain.','Liquid mempunyai volume tetapi mengambil shape container.', []),S('💨','Gas','Particle gas berjauhan dan bergerak bebas.','Gas mengembang memenuhi container dan mudah dimampatkan berbanding liquid.', []),S('⚡','Plasma','Pada energy tinggi, atom boleh ionize lalu menghasilkan plasma dengan charged particles.','Sun dan lightning mengandungi plasma.', []),S('🔥','Phase change','Melting, freezing, evaporation, condensation dan sublimation melibatkan perubahan energy dan susunan particle.','Temperature boleh kekal hampir constant semasa phase change kerana energy digunakan untuk mengubah intermolecular arrangement.', [])],

  satellite:[S('🛰️','Apa itu satellite?','Satellite ialah objek yang mengorbit objek lain; Moon ialah natural satellite, manakala manusia membina artificial satellite.','Artificial satellite digunakan untuk communication, navigation, weather, Earth observation dan science.', []),S('🌍','Jenis orbit','Low Earth Orbit dekat dan sesuai untuk imaging serta banyak constellation; geostationary orbit jauh dan nampak tetap di langit relatif kepada Earth.','Orbit dipilih mengikut mission, coverage dan latency.', []),S('📡','Communication','Satellite menerima signal, memproses/amplify dan menghantar semula ke kawasan lain.','Frequency, antenna beam dan ground station menentukan link performance.', []),S('🧭','Navigation','GNSS satellite menghantar time signal yang sangat tepat.','Receiver mengukur arrival time daripada beberapa satellite untuk mengira position.', []),S('🗑️','Space debris','Old satellite dan fragments boleh kekal dalam orbit dan menjadi collision risk.','Tracking, end-of-life disposal dan collision avoidance semakin penting.', [])],
  internet:[S('🌐','Network of networks','Internet ialah rangkaian besar yang menghubungkan network melalui standard protocol.','Ia bukan satu “cloud” fizikal tunggal — data bergerak melalui router, fiber, cable, radio dan data center.', []),S('📦','Packet','Data dipecahkan kepada packet yang boleh mengambil laluan berbeza sebelum disusun semula.','Protocol seperti IP membantu addressing dan routing.', []),S('🔎','DNS','DNS menukar nama seperti example.com kepada IP address yang boleh digunakan network.','Ia berfungsi seperti distributed directory, bukan satu server global sahaja.', []),S('🔐','HTTPS','HTTPS menggunakan encryption supaya pihak di tengah lebih sukar membaca atau mengubah traffic.','Certificate membantu browser mengesahkan identity website.', []),S('⏱️','Latency vs speed','Bandwidth ialah berapa banyak data boleh dihantar per unit time; latency ialah masa delay.','Connection boleh mempunyai bandwidth tinggi tetapi masih rasa lambat jika latency atau server response buruk.', [])],
  robot:[S('🤖','Robot = sense + decide + act','Robot biasanya mempunyai sensor, controller/computer dan actuator.','Sensor membaca dunia, software membuat decision, actuator menggerakkan badan atau tool.', []),S('👁️','Sensor','Camera, lidar, ultrasonic, encoder, force sensor dan IMU memberi jenis maklumat berbeza.','Tiada satu sensor yang sempurna; sensor fusion menggabungkan beberapa sumber.', []),S('🦾','Actuator','Motor, servo, hydraulic dan pneumatic actuator menghasilkan movement.','Gearbox menukar speed dan torque untuk tugas tertentu.', []),S('🧠','Autonomy','Sesetengah robot ikut program tetap; yang lain menggunakan planning, computer vision atau machine learning.','“AI robot” masih terikat pada sensor, data, safety constraints dan task yang direka.', []),S('🏭','Kegunaan','Robot digunakan dalam factory, warehouse, surgery, exploration dan rumah.','Kelebihan utama ialah consistency, precision atau operasi di tempat berbahaya — bukan semestinya menggantikan semua kerja manusia.', [])],
  computer:[S('💻','Input → process → output','Computer menerima input, memproses instruction dan menghasilkan output sambil menyimpan data.','Semua ini berlaku melalui hardware yang dikawal oleh software.', []),S('🧠','CPU','CPU menjalankan instruction, arithmetic dan control flow.','Modern CPU mempunyai banyak core, cache dan pipeline untuk melakukan banyak kerja dengan cepat.', []),S('🧮','Binary','Digital computer menyimpan data menggunakan state yang boleh diwakili sebagai 0 dan 1.','Text, image, sound dan video semuanya akhirnya dikodkan sebagai bit pattern.', []),S('🗄️','RAM vs storage','RAM pantas tetapi biasanya volatile; SSD/storage menyimpan data walaupun power off.','Program dimuat dari storage ke RAM supaya CPU boleh akses dengan cepat.', []),S('🌐','Software layers','Operating system mengurus hardware dan menyediakan service kepada apps.','App pula menggunakan API dan library supaya developer tidak perlu mengawal setiap transistor secara langsung.', [])]
};

const DEEP_SOURCES={
  'solar-system':['NASA Science — Solar System Facts','NASA Science — Planetary Systems'],
  sun:['NASA Science — Sun: Facts','NASA Science — Layers of the Sun'],
  mercury:['NASA Science — Mercury'],venus:['NASA Science — Venus'],earth:['NASA Science — Earth'],mars:['NASA Science — Mars'],jupiter:['NASA Science — Jupiter'],saturn:['NASA Science — Saturn'],uranus:['NASA Science — Uranus'],neptune:['NASA Science — Neptune'],moon:['NASA Science — Earth’s Moon']
};
