const ENCYCLOPEDIA = {
  wikiTitle: {
    'solar-system':'Solar System','sun':'Sun','mercury':'Mercury (planet)','venus':'Venus','earth':'Earth','mars':'Mars','jupiter':'Jupiter','saturn':'Saturn','uranus':'Uranus','neptune':'Neptune','moon':'Moon','rocket':'Rocket',
    'elephant':'Elephant','lion':'Lion','giraffe':'Giraffe','tiger':'Tiger','zebra':'Zebra','penguin':'Penguin','dolphin':'Dolphin','eagle':'Eagle',
    'car':'Car','airplane':'Airplane','train':'Train','ship':'Ship','excavator':'Excavator','bicycle':'Bicycle',
    'volcano':'Volcano','earthquake':'Earthquake','rain':'Rain','cloud':'Cloud','river':'River','mountain':'Mountain',
    'shark':'Shark','octopus':'Octopus','whale':'Whale','coral':'Coral reef','deep-sea':'Deep sea',
    'trex':'Tyrannosaurus','triceratops':'Triceratops','brachiosaurus':'Brachiosaurus','raptor':'Velociraptor','fossil':'Fossil',
    'seed':'Seed','roots':'Root','leaf':'Leaf','flower':'Flower','tree':'Tree','photosynthesis':'Photosynthesis',
    'heart':'Heart','lungs':'Lung','brain':'Brain','bones':'Bone','stomach':'Stomach','senses':'Sense',
    'traffic-light':'Traffic light','fan':'Fan (machine)','elevator':'Elevator','electricity':'Electricity',
    'continents':'Continent','malaysia':'Malaysia','japan':'Japan','egypt':'Egypt','flags':'Flag',
    'gravity':'Gravity','magnet':'Magnet','light':'Light','sound':'Sound','states':'State of matter',
    'satellite':'Satellite','internet':'Internet','robot':'Robot','computer':'Computer'
  },
  field: {
    space:['Astronomi','Sistem Suria'],animals:['Biologi','Haiwan'],vehicles:['Kejuruteraan','Pengangkutan'],'earth-world':['Sains Bumi','Alam Semula Jadi'],ocean:['Biologi Marin','Lautan'],dinosaurs:['Paleontologi','Prasejarah'],plants:['Botani','Tumbuhan'],body:['Biologi Manusia','Tubuh'],machines:['Kejuruteraan','Mesin'],world:['Geografi','Dunia'],science:['Sains','Konsep Asas'],technology:['Teknologi','Ciptaan'],english:['Bahasa','English']
  },
  glossary: {
    'nuclear fusion':['Nuclear fusion','Proses apabila nukleus atom ringan bergabung dan membebaskan tenaga.'],
    'fusion':['Fusion','Gabungan nukleus atom yang boleh menghasilkan tenaga.'],
    'core':['Core','Bahagian paling dalam sesuatu objek; bagi Matahari, di sinilah kebanyakan tenaga dihasilkan.'],
    'photosphere':['Photosphere','Lapisan Matahari yang kita nampak sebagai permukaan bercahaya.'],
    'corona':['Corona','Atmosfera luar Matahari yang sangat panas dan memanjang jauh ke angkasa.'],
    'solar wind':['Solar wind','Aliran zarah bercas daripada Matahari yang bergerak melalui Sistem Suria.'],
    'orbit':['Orbit','Laluan sesuatu objek apabila bergerak mengelilingi objek lain akibat graviti.'],
    'gravity':['Gravity','Daya tarikan antara objek yang mempunyai jisim.'],
    'atmosphere':['Atmosphere','Lapisan gas yang mengelilingi planet atau objek langit.'],
    'habitat':['Habitat','Tempat semula jadi sesuatu hidupan tinggal dan mendapatkan makanan serta perlindungan.'],
    'herbivore':['Herbivore','Haiwan yang terutama memakan tumbuhan.'],
    'carnivore':['Carnivore','Haiwan yang terutama memakan haiwan lain.'],
    'predator':['Predator','Haiwan yang memburu hidupan lain untuk makanan.'],
    'ecosystem':['Ecosystem','Komuniti hidupan dan persekitarannya yang saling berinteraksi.'],
    'thrust':['Thrust','Daya yang menolak kenderaan seperti kapal terbang atau roket ke hadapan.'],
    'lift':['Lift','Daya ke atas yang membantu kapal terbang kekal di udara.'],
    'drag':['Drag','Rintangan udara yang melawan pergerakan objek.'],
    'magma':['Magma','Batuan cair yang berada di bawah permukaan Bumi.'],
    'lava':['Lava','Magma yang telah keluar ke permukaan Bumi.'],
    'tectonic':['Tectonic plate','Bahagian besar kerak/litosfera Bumi yang bergerak perlahan.'],
    'molecule':['Molecule','Kumpulan dua atau lebih atom yang terikat bersama.'],
    'photosynthesis':['Photosynthesis','Proses tumbuhan menggunakan cahaya untuk menghasilkan makanan daripada air dan karbon dioksida.'],
    'chlorophyll':['Chlorophyll','Pigmen hijau pada tumbuhan yang membantu menyerap tenaga cahaya.'],
    'oxygen':['Oxygen','Gas yang diperlukan oleh kebanyakan hidupan untuk respirasi.'],
    'fossil':['Fossil','Sisa atau kesan hidupan purba yang terawet dalam batuan atau bahan lain.'],
    'extinct':['Extinct','Keadaan apabila sesuatu spesies sudah tidak mempunyai individu hidup.'],
    'nerve':['Nerve','Struktur yang membawa isyarat antara otak, saraf tunjang dan bahagian badan.'],
    'artery':['Artery','Salur darah yang membawa darah keluar dari jantung.'],
    'neuron':['Neuron','Sel khusus dalam sistem saraf yang menghantar isyarat.'],
    'current':['Electric current','Aliran cas elektrik melalui sesuatu bahan atau litar.'],
    'circuit':['Circuit','Laluan lengkap yang membolehkan arus elektrik mengalir.'],
    'frequency':['Frequency','Berapa kerap sesuatu getaran atau kitaran berlaku dalam satu tempoh.'],
    'matter':['Matter','Apa-apa yang mempunyai jisim dan mengambil ruang.'],
    'satellite':['Satellite','Objek yang mengorbit objek lain; boleh semula jadi atau buatan manusia.'],
    'internet':['Internet','Rangkaian besar yang menghubungkan banyak rangkaian komputer di seluruh dunia.']
  }
};
